export type SiteConfig = typeof siteConfig;

export const siteConfig = {
  name: "KL Renovator",
  parentCompany: "Multicore Dynamic Resources",
  tagline: "Expert Aircond Servicing, Chemical Overhaul & Repair KL & Selangor",
  description:
    "KL Renovator provides professional residential and commercial aircond servicing in Kuala Lumpur & Selangor. Serving Batu Caves, Ampang, Cheras, Petaling Jaya, Subang Jaya, Puchong, Shah Alam, Damansara, Klang, Kajang, Bangsar, Mont Kiara, Setapak, Sentul, Putrajaya & Cyberjaya. Specialized in Pressure Chemical Wash, Chemical Overhaul, Precision Gas Top-ups (R22, R410A, R32 balancing), Troubleshooting & New Installations for Daikin, Panasonic, Mitsubishi, York, LG, Midea & Samsung. Fast response and transparent pricing across Klang Valley.",

  phone: "+60182983573",
  phoneDisplay: "+60 18-298 3573",
  whatsapp: "60182983573",
  whatsappLink: "https://wa.me/60182983573?text=Hi%20KL%20Renovator,%20I%20want%20to%20book%20an%20aircond%20service%20for%20my%20home/office.",
  email: "info@klrenovator.com",
  address: "Selayang, 68100 Selangor, Malaysia",
  addressStreet: "Megnavilla Selayang",
  addressCity: "Selayang",
  addressPostal: "68100",
  addressState: "Selangor",
  addressCountry: "MY",
  geoLat: 3.22050,
  geoLng: 101.64120,
  hours: "Mon–Sun · 9:00 AM – 6:00 PM (Everyday Open)",
  googleMapsEmbed: "https://maps.app.goo.gl/dG5WWYBCotRQzvRJA",
  googleBusinessProfile: "https://share.google/HhXvqWDkefZ5bzNdL",
  reviewCount: 500,
  reviewRating: 4.9,

  navItems: [
    { label: "Home", href: "/" },
    { label: "Services", href: "/services" },
    { label: "Gallery", href: "/gallery" },
    { label: "About", href: "/about" },
    { label: "FAQ", href: "/faq" },
    { label: "Contact", href: "/contact" },
  ],

  areas: [
    "Kuala Lumpur", "Selangor", "Batu Caves", "Ampang", "Cheras",
    "Petaling Jaya", "Subang Jaya", "Puchong", "Shah Alam", "Damansara",
    "Klang", "Kajang", "Bangsar", "Mont Kiara", "Setapak",
    "Sentul", "Putrajaya", "Cyberjaya",
  ],

  // Area pages data — each area gets a dedicated SEO page at /areas/[slug]
  areaPages: [
    {
      slug: "petaling-jaya",
      name: "Petaling Jaya",
      shortName: "PJ",
      state: "Selangor",
      lat: 3.10726,
      lng: 101.60671,
      population: "600,000+",
      landmarks: ["SS2", "Damansara Utama", "Tropicana", "Kelana Jaya", "Ara Damansara", "Taman Jaya"],
      description: "Aircond service Petaling Jaya (PJ) — KL Renovator dispatches trained HVAC technicians to all PJ zones including SS2, Damansara Utama, Tropicana, Kelana Jaya and Ara Damansara. Same-day booking available.",
      metaTitle: "Aircond Service Petaling Jaya (PJ) | KL Renovator — From RM 99",
      metaDesc: "Professional aircond servicing in Petaling Jaya. Chemical wash, overhaul, gas top-up, repairs. All brands. Same-day available. Call +60182983573.",
    },
    {
      slug: "cheras",
      name: "Cheras",
      shortName: "Cheras",
      state: "Kuala Lumpur / Selangor",
      lat: 3.08452,
      lng: 101.73421,
      population: "400,000+",
      landmarks: ["Taman Connaught", "Batu 9", "Batu 11", "Miharja", "Maluri", "Taman Mutiara"],
      description: "Aircond service Cheras — KL Renovator covers all Cheras zones including Taman Connaught, Batu 9, Batu 11, Miharja and Maluri. Fast response, transparent pricing, all brands supported.",
      metaTitle: "Aircond Service Cheras KL | KL Renovator — Chemical Wash From RM 160",
      metaDesc: "Expert aircond servicing in Cheras. Chemical wash, overhaul, gas top-up & repairs for all brands. Same-day available. Call +60182983573.",
    },
    {
      slug: "shah-alam",
      name: "Shah Alam",
      shortName: "Shah Alam",
      state: "Selangor",
      lat: 3.08507,
      lng: 101.53281,
      population: "700,000+",
      landmarks: ["Section 7", "Section 13", "Section 17", "Setia Alam", "Kota Kemuning", "Bukit Jelutong"],
      description: "Aircond service Shah Alam — KL Renovator services all Shah Alam sections including Section 7, 13, 17, Setia Alam, Kota Kemuning and Bukit Jelutong. Professional HVAC technicians, same-day slots.",
      metaTitle: "Aircond Service Shah Alam | KL Renovator — Same-Day Available",
      metaDesc: "Professional aircond servicing in Shah Alam. All sections covered. Chemical wash, overhaul, installations & repairs. Call +60182983573.",
    },
    {
      slug: "subang-jaya",
      name: "Subang Jaya",
      shortName: "Subang",
      state: "Selangor",
      lat: 3.05018,
      lng: 101.58983,
      population: "700,000+",
      landmarks: ["USJ", "SS15", "SS16", "Taipan", "Sunway", "Putra Heights"],
      description: "Aircond service Subang Jaya — KL Renovator covers USJ, SS15, SS16, Taipan, Sunway and Putra Heights. Expert chemical wash, overhaul, gas top-up and repairs for all major brands.",
      metaTitle: "Aircond Service Subang Jaya & USJ | KL Renovator — From RM 99",
      metaDesc: "Expert aircond service in Subang Jaya & USJ. Chemical wash, overhaul, gas top-up for Daikin, Panasonic, Mitsubishi & more. Call +60182983573.",
    },
    {
      slug: "ampang",
      name: "Ampang",
      shortName: "Ampang",
      state: "Selangor / KL",
      lat: 3.14778,
      lng: 101.76267,
      population: "300,000+",
      landmarks: ["Ampang Jaya", "Taman Muda", "Ukay Perdana", "Pandan Indah", "Taman Keramat"],
      description: "Aircond service Ampang — KL Renovator dispatches to Ampang Jaya, Taman Muda, Ukay Perdana, Pandan Indah and Taman Keramat. Fast response, honest pricing, no hidden charges.",
      metaTitle: "Aircond Service Ampang | KL Renovator — Fast Response, No Hidden Fees",
      metaDesc: "Professional aircond servicing in Ampang & Ampang Jaya. Chemical wash, overhaul, repairs & installations. Call +60182983573.",
    },
    {
      slug: "puchong",
      name: "Puchong",
      shortName: "Puchong",
      state: "Selangor",
      lat: 3.02726,
      lng: 101.61811,
      population: "300,000+",
      landmarks: ["IOI Mall", "Bandar Puteri", "Puchong Jaya", "Bukit Puchong", "Taman Wawasan"],
      description: "Aircond service Puchong — KL Renovator covers Bandar Puteri, Puchong Jaya, Bukit Puchong and Taman Wawasan. Expert HVAC technicians, same-day service, transparent pricing.",
      metaTitle: "Aircond Service Puchong | KL Renovator — Expert HVAC From RM 99",
      metaDesc: "Trusted aircond service in Puchong. Chemical wash, gas top-up, overhaul & repairs for all brands. Same-day available. Call +60182983573.",
    },
    {
      slug: "klang",
      name: "Klang",
      shortName: "Klang",
      state: "Selangor",
      lat: 3.04465,
      lng: 101.44694,
      population: "400,000+",
      landmarks: ["Bukit Tinggi", "Bandar Baru Klang", "Meru", "Port Klang", "Pandamaran"],
      description: "Aircond service Klang — KL Renovator services Bukit Tinggi, Bandar Baru Klang, Meru, Port Klang and Pandamaran. All brands serviced, competitive rates, 1-month warranty.",
      metaTitle: "Aircond Service Klang | KL Renovator — All Brands, Transparent Pricing",
      metaDesc: "Professional aircond service in Klang. Bukit Tinggi, Meru, Port Klang covered. Chemical wash, repairs & installations. Call +60182983573.",
    },
    {
      slug: "kajang",
      name: "Kajang",
      shortName: "Kajang",
      state: "Selangor",
      lat: 2.99330,
      lng: 101.78820,
      population: "250,000+",
      landmarks: ["Bangi", "Semenyih", "Cheras Baru", "Taman Kajang Maju", "Sungai Chua"],
      description: "Aircond service Kajang — KL Renovator covers Kajang, Bangi, Semenyih and surrounding areas. Expert aircond chemical wash, overhaul, gas top-up and repairs for all brands.",
      metaTitle: "Aircond Service Kajang & Bangi | KL Renovator — Same-Day Service",
      metaDesc: "Expert aircond servicing in Kajang and Bangi. Chemical wash, overhaul & repairs for all brands. Fast response. Call +60182983573.",
    },
    {
      slug: "batu-caves",
      name: "Batu Caves",
      shortName: "Batu Caves",
      state: "Selangor",
      lat: 3.23726,
      lng: 101.68316,
      population: "200,000+",
      landmarks: ["Taman Batu Muda", "Sri Murugan", "Taman Selayang", "Kepong Baru"],
      description: "Aircond service Batu Caves — KL Renovator covers Batu Caves, Taman Batu Muda, Taman Selayang and Kepong Baru. Professional HVAC team, same-day slots, honest pricing.",
      metaTitle: "Aircond Service Batu Caves | KL Renovator — Professional HVAC Team",
      metaDesc: "Professional aircond servicing in Batu Caves & Selayang. Chemical wash, overhaul & repairs. All brands. Call +60182983573.",
    },
    {
      slug: "damansara",
      name: "Damansara",
      shortName: "Damansara",
      state: "Selangor / KL",
      lat: 3.15283,
      lng: 101.61278,
      population: "300,000+",
      landmarks: ["Damansara Perdana", "Damansara Damai", "Kota Damansara", "Mutiara Damansara", "One Utama"],
      description: "Aircond service Damansara — KL Renovator covers Damansara Perdana, Damansara Damai, Kota Damansara and Mutiara Damansara. Expert servicing for condominiums and landed homes.",
      metaTitle: "Aircond Service Damansara | KL Renovator — Condo & Landed Specialists",
      metaDesc: "Expert aircond service in Damansara. All zones covered. Chemical wash, overhaul, gas top-up for Daikin, Panasonic & more. Call +60182983573.",
    },
    {
      slug: "bangsar",
      name: "Bangsar",
      shortName: "Bangsar",
      state: "Kuala Lumpur",
      lat: 3.12897,
      lng: 101.67434,
      population: "150,000+",
      landmarks: ["Bangsar Baru", "Bangsar South", "Kerinchi", "Pantai Dalam", "Mid Valley"],
      description: "Aircond service Bangsar — KL Renovator covers Bangsar Baru, Bangsar South, Kerinchi and Pantai Dalam. Professional HVAC service for condominiums, apartments and offices.",
      metaTitle: "Aircond Service Bangsar KL | KL Renovator — Condo Specialist",
      metaDesc: "Professional aircond servicing in Bangsar & Bangsar South. Chemical wash, overhaul & repairs. All brands. Call +60182983573.",
    },
    {
      slug: "mont-kiara",
      name: "Mont Kiara",
      shortName: "Mont Kiara",
      state: "Kuala Lumpur",
      lat: 3.17278,
      lng: 101.64876,
      population: "100,000+",
      landmarks: ["Sri Hartamas", "Solaris Dutamas", "Duta Nusantara", "Plaza Mont Kiara"],
      description: "Aircond service Mont Kiara — KL Renovator provides professional HVAC servicing for condominiums and luxury properties in Mont Kiara, Sri Hartamas and Solaris Dutamas.",
      metaTitle: "Aircond Service Mont Kiara | KL Renovator — Luxury Condo Specialist",
      metaDesc: "Professional aircond servicing in Mont Kiara & Sri Hartamas. Chemical wash, overhaul & repairs for condos. Call +60182983573.",
    },
    {
      slug: "setapak",
      name: "Setapak",
      shortName: "Setapak",
      state: "Kuala Lumpur",
      lat: 3.19383,
      lng: 101.71247,
      population: "200,000+",
      landmarks: ["Taman Setapak", "Wangsa Maju", "Gombak", "Taman Sri Rampai"],
      description: "Aircond service Setapak — KL Renovator covers Setapak, Wangsa Maju, Taman Sri Rampai and surrounding areas. Fast response, transparent pricing, all brands serviced.",
      metaTitle: "Aircond Service Setapak & Wangsa Maju | KL Renovator",
      metaDesc: "Expert aircond service in Setapak & Wangsa Maju. Chemical wash, overhaul & repairs. Fast response. Call +60182983573.",
    },
    {
      slug: "sentul",
      name: "Sentul",
      shortName: "Sentul",
      state: "Kuala Lumpur",
      lat: 3.18162,
      lng: 101.68923,
      population: "150,000+",
      landmarks: ["Sentul Park", "Jalan Ipoh", "Taman Wahyu", "Brickfields"],
      description: "Aircond service Sentul — KL Renovator covers Sentul, Taman Wahyu, Jalan Ipoh corridor and surrounding areas. Professional HVAC team with same-day slots available.",
      metaTitle: "Aircond Service Sentul KL | KL Renovator — Same-Day Slots",
      metaDesc: "Professional aircond servicing in Sentul KL. Chemical wash, overhaul & repairs for all brands. Same-day available. Call +60182983573.",
    },
    {
      slug: "selayang",
      name: "Selayang",
      shortName: "Selayang",
      state: "Selangor",
      lat: 3.22050,
      lng: 101.64120,
      population: "250,000+",
      landmarks: ["Selayang Mall", "Batu Caves", "Taman Selayang Baru", "Gombak"],
      description: "Aircond service Selayang — KL Renovator is headquartered in Selayang, providing ultra-fast HVAC response across Selayang Baru, Gombak and all surrounding zones.",
      metaTitle: "Aircond Service Selayang | KL Renovator — Headquartered Here",
      metaDesc: "KL Renovator is based in Selayang. Expert aircond chemical wash, overhaul, gas top-up & repairs. Fastest response. Call +60182983573.",
    },
    {
      slug: "putrajaya",
      name: "Putrajaya",
      shortName: "Putrajaya",
      state: "Putrajaya",
      lat: 2.92636,
      lng: 101.69625,
      population: "100,000+",
      landmarks: ["Presinct 1", "Presinct 9", "Presinct 14", "Presinct 18", "Cyberjaya"],
      description: "Aircond service Putrajaya — KL Renovator covers all Putrajaya presincts. Professional HVAC team for government quarters, condos and commercial buildings.",
      metaTitle: "Aircond Service Putrajaya | KL Renovator — All Presincts Covered",
      metaDesc: "Professional aircond servicing in Putrajaya. All presincts covered. Chemical wash, overhaul & repairs. Call +60182983573.",
    },
    {
      slug: "cyberjaya",
      name: "Cyberjaya",
      shortName: "Cyberjaya",
      state: "Selangor",
      lat: 2.92160,
      lng: 101.65348,
      population: "80,000+",
      landmarks: ["Shaftsbury", "Tamarind Square", "Cyberia", "Jade Hills", "Kotaray"],
      description: "Aircond service Cyberjaya — KL Renovator provides professional HVAC servicing for tech parks, condominiums and offices in Cyberjaya including Shaftsbury, Cyberia and Tamarind Square.",
      metaTitle: "Aircond Service Cyberjaya | KL Renovator — Tech Hub HVAC Specialist",
      metaDesc: "Expert aircond servicing in Cyberjaya. Chemical wash, overhaul & repairs for condos and offices. All brands. Call +60182983573.",
    },
  ],

  brandsSupported: ["Daikin", "Panasonic", "Mitsubishi", "York", "Midea", "LG", "Samsung"],

  services: [
    {
      slug: "installation",
      title: "New Unit Installation & Dismantling",
      short: "Professional residential and commercial AC setup with clean cable routing. Dismantling of old models and installation of high-efficiency inverter units.",
      startPrice: 199,
      icon: "plug",
      targetProblem: "Upgrading old non-inverter systems, moving into a new office or home.",
      category: "both" as const,
    },
    {
      slug: "basic-servicing",
      title: "Basic Servicing / Routine Maintenance",
      short: "Regular standard aircond filter cleaning and multi-point diagnostic check to maintain peak energy efficiency and extend unit lifespan.",
      startPrice: 99,
      icon: "wrench",
      targetProblem: "Routine 3–6 month checkup, energy efficiency optimization, preventive care.",
      category: "residential" as const,
    },
    {
      slug: "chemical-wash",
      title: "Pressure Chemical Wash",
      short: "Deep high-pressure chemical cleaning to remove stubborn mould, dust, bacteria and dramatically improve cooling airflow and air quality.",
      startPrice: 160,
      icon: "flask-conical",
      targetProblem: "Slow cooling, foul smell, low airflow, dusty air extraction.",
      category: "both" as const,
    },
    {
      slug: "chemical-overhaul",
      title: "Chemical Overhaul",
      short: "Complete dismantling of the indoor unit for the ultimate deep-clean. Permanently resolves severe water leaking, ice formation, and extreme blockage.",
      startPrice: 220,
      icon: "sparkles",
      targetProblem: "Water leaking, ice formation, complete blockage, system choking.",
      category: "both" as const,
    },
    {
      slug: "gas-topup",
      title: "Gas Top-Up / Precision Balancing",
      short: "Precision refrigerant balancing and pressure level top-up for eco-friendly R32, R410A, and traditional R22 systems. Leak check included.",
      startPrice: 100,
      icon: "gauge",
      targetProblem: "Aircond running but blowing warm air, low gas pressure.",
      category: "both" as const,
    },
    {
      slug: "repair",
      title: "Troubleshooting & Repairs",
      short: "Expert diagnosis and replacement of faulty aircond parts — capacitors, fan motors, sensor coils, PCB boards, or copper wiring. Quote before work.",
      startPrice: 88,
      icon: "settings",
      targetProblem: "Noisy outdoor unit, sudden auto shut-off, blinking timer light, wiring sparks.",
      category: "both" as const,
    },
    {
      slug: "dismantling-relocation",
      title: "Dismantle & Relocation",
      short: "Safe and risk-free extraction of existing indoor/outdoor units with proper refrigerant pump-down and sealing. Full reinstall at new location.",
      startPrice: 90,
      icon: "move",
      targetProblem: "House moving, shop shifting, office renovation and AC relocation.",
      category: "both" as const,
    },
    {
      slug: "ceiling-cassette",
      title: "Ceiling Cassette Solutions",
      short: "Heavy-duty commercial ceiling cassette servicing, chemical wash, VRF/VRV installation and scheduled maintenance for corporate and retail layouts.",
      startPrice: 290,
      icon: "layout-grid",
      targetProblem: "Commercial office hot spots, VRF/VRV systems, corporate annual maintenance needs.",
      category: "commercial" as const,
    },
  ],

  pricing: {
    chemicalWash: {
      title: "Pressure Chemical Wash",
      rows: [
        { label: "Wall-Mounted · 1.0 – 1.5 HP", price: "RM 160" },
        { label: "Wall-Mounted · 2.0 – 2.5 HP", price: "RM 220" },
        { label: "Wall-Mounted · 3.0 HP", price: "RM 250" },
        { label: "Wall-Mounted · 4.0 – 5.0 HP", price: "RM 280" },
        { label: "Ceiling Cassette · 1.0 – 1.5 HP", price: "RM 220" },
        { label: "Ceiling Cassette · 2.0 – 3.0 HP", price: "RM 280" },
        { label: "Ceiling Cassette · 4.0 – 5.0 HP", price: "RM 350" },
        { label: "Floor Standing · 3.0 – 5.0 HP", price: "RM 320" },
        { label: "Window Unit · 1.0 – 2.0 HP", price: "RM 130" },
        { label: "Window Unit · 2.5 – 3.0 HP", price: "RM 160" },
      ],
    },
    chemicalOverhaul: {
      title: "Chemical Overhaul",
      rows: [
        { label: "Wall-Mounted · 1.0 – 1.5 HP", price: "RM 220" },
        { label: "Wall-Mounted · 2.0 – 2.5 HP", price: "RM 280" },
        { label: "Wall-Mounted · 3.0 HP", price: "RM 350" },
        { label: "Ceiling Cassette · 1.0 – 3.0 HP", price: "RM 380 – 480" },
      ],
    },
    basicServicing: {
      title: "Basic Servicing / Cleaning",
      rows: [
        { label: "Wall-Mounted · 1.0 – 1.5 HP", price: "RM 99" },
        { label: "Wall-Mounted · 2.0 – 2.5 HP", price: "RM 150" },
        { label: "Wall-Mounted · 3.0 HP", price: "RM 180" },
        { label: "Ceiling Cassette · 1.0 – 1.5 HP", price: "RM 150" },
        { label: "Ceiling Cassette · 2.0 – 3.0 HP", price: "RM 200" },
        { label: "Ceiling Cassette · 3.5 – 5.0 HP", price: "RM 250" },
      ],
    },
    gasTopup: {
      title: "Gas Top-Up Balancing",
      rows: [
        { label: "R22 Freon Gas · 1.0 HP", price: "RM 80 – 100" },
        { label: "R22 Freon Gas · 1.5 – 2.0 HP", price: "RM 100 – 130" },
        { label: "R22 Freon Gas · 2.5 – 3.0 HP", price: "RM 130 – 160" },
        { label: "R410A Eco Gas · 1.0 HP", price: "RM 100 – 120" },
        { label: "R410A Eco Gas · 1.5 – 2.0 HP", price: "RM 120 – 150" },
        { label: "R410A Eco Gas · 2.5 – 3.0 HP", price: "RM 150 – 180" },
        { label: "R32 Next-Gen Gas · 1.0 HP", price: "RM 130 – 150" },
        { label: "R32 Next-Gen Gas · 1.5 – 2.0 HP", price: "RM 150 – 180" },
        { label: "R32 Next-Gen Gas · 2.5 – 3.0 HP", price: "RM 180 – 200" },
      ],
    },
    repair: {
      title: "Troubleshooting & Component Repair",
      rows: [
        { label: "Diagnostic / Troubleshoot Fee (Waived with repair)", price: "RM 88" },
        { label: "Copper Sensor Replacement", price: "RM 150" },
        { label: "Outdoor Capacitor Replacement", price: "RM 150" },
        { label: "Blower / Fan Motor Replacement", price: "RM 200 – 500" },
        { label: "PCB / Main Electronic Control Board", price: "RM 300 – 800" },
        { label: "Compressor Replacement Work", price: "RM 800 – 2,000" },
        { label: "Thermostat Mechanism Control", price: "RM 120 – 200" },
        { label: "Internal Water Drain Pump", price: "RM 200 – 400" },
      ],
    },
    installation: {
      title: "Installation Work (Labour & Standard Piping)",
      rows: [
        { label: "Wall-Mounted Setup · 1.0 – 1.5 HP", price: "RM 250" },
        { label: "Wall-Mounted Setup · 2.0 – 2.5 HP", price: "RM 280" },
        { label: "Wall-Mounted Setup · 3.0 HP", price: "RM 350" },
        { label: "Wall-Mounted Setup · 4.0 – 5.0 HP", price: "RM 550" },
        { label: "Ceiling Cassette Setup · 1.0 – 1.5 HP", price: "RM 250" },
        { label: "Ceiling Cassette Setup · 2.0 – 3.0 HP", price: "RM 350" },
        { label: "Ceiling Cassette Setup · 3.5 – 6.0 HP", price: "RM 400" },
      ],
      note: "Standard professional installation includes free 7 ft copper pipe, heavy duty wiring, and system drainage layout.",
    },
    materials: {
      title: "Additional High-Quality Materials",
      rows: [
        { label: "Premium Copper Pipe · 1.0 – 2.0 HP", price: "RM 17 / ft" },
        { label: "Premium Copper Pipe · 2.5 – 3.5 HP", price: "RM 26 / ft" },
        { label: "Standard Outdoor Bracket", price: "RM 45" },
        { label: "Indoor Universal Bracket", price: "RM 25" },
        { label: "PVC Casing Wire / Copper Pipe", price: "RM 6 – 12 / ft" },
        { label: "Dedicated Electrical Plug Point Installation", price: "RM 100" },
        { label: "Wall Hacking & Concealment Work", price: "RM 6 / ft" },
        { label: "High-Rise / Difficult Access Charge", price: "RM 50 – 150" },
        { label: "Standard Metal Cable Tray (White/Orange/HDG)", price: "RM 16 / ft" },
      ],
    },
    contracts: {
      title: "Annual Corporate & Residential Maintenance Contracts",
      rows: [
        { label: "Residential Package · 2 – 4 units / year contract", price: "RM 499" },
        { label: "Residential Package · 5+ units / year contract", price: "RM 999" },
      ],
    },
  },

  volumeDiscounts: [
    { units: "2 – 3 units", off: "5% off instant booking discount" },
    { units: "4 – 8 units", off: "10% off instant booking discount" },
    { units: "8+ units", off: "15% off instant booking discount" },
  ],

  stats: [
    { label: "Happy Klang Valley Customers", value: "5,000+" },
    { label: "Years HVAC Experience", value: "10+" },
    { label: "5-Star Verified Reviews", value: "500+" },
    { label: "Emergency Response Time", value: "< 30 min" },
  ],

  links: {
    whatsapp: "https://wa.me/60182983573",
    facebook: "https://www.facebook.com/share/1HV3kAqC6V/",
    instagram: "https://www.instagram.com/klrneovator?igsh=MTNqb3p1NDExZ3Boeg==",
    tiktok: "https://www.tiktok.com/@klrenovator?_r=1&_t=ZS-96tR1k7aVU5",
    googleMaps: "https://maps.app.goo.gl/dG5WWYBCotRQzvRJA",
    googleBusiness: "https://share.google/HhXvqWDkefZ5bzNdL",
  },
};
