export type SiteConfig = typeof siteConfig;

export const siteConfig = {
  name: "KL Renovator",
  parentCompany: "Multicore Dynamics Resources",
  legalName: "Multicore Dynamics Resources",
  ssm: "003765188-T",
  ssmFull: "202503227236 (003765188-T)",
  tagline: "Expert Aircond Servicing, Chemical Overhaul & Repair KL & Selangor",
  description:
    "KL Renovator provides professional residential and commercial aircond servicing in Kuala Lumpur & Selangor. Serving Batu Caves, Ampang, Cheras, Petaling Jaya, Subang Jaya, Puchong, Shah Alam, Damansara, Klang, Kajang, Bangsar, Mont Kiara, Setapak, Wangsa Maju, Kepong, Sri Petaling, Bukit Jalil, Kota Damansara, Ara Damansara, Sunway, USJ, Port Klang, Bukit Tinggi, Setia Alam, Meru, Rawang, Kundang, Bangi, Semenyih, Balakong, Seri Kembangan, Pandan Indah, Putrajaya, Cyberjaya & Dengkil. Specialized in Pressure Chemical Wash, Chemical Overhaul, Precision Gas Top-ups (R22, R410A, R32 balancing), Troubleshooting & New Installations for Daikin, Panasonic, Mitsubishi, York, LG, Midea & Samsung. Fast response and transparent pricing across Klang Valley.",

  phone: "+60182983573",
  phoneDisplay: "+60 18-298 3573",
  whatsapp: "60182983573",
  whatsappLink: "https://wa.me/60182983573?text=Hi%20KL%20Renovator,%20I%20want%20to%20book%20an%20aircond%20service%20for%20my%20home/office.",
  email: "info@klrenovator.com",
  address: "A-22-09 Magnaville Selayang, 68100 Batu Caves, Selangor, Malaysia",
  addressStreet: "A-22-09 Magnaville Selayang",
  addressCity: "Batu Caves",
  addressPostal: "68100",
  addressState: "Selangor",
  addressCountry: "MY",
  geoLat: 3.22050,
  geoLng: 101.64120,
  hours: "Mon–Sun · 9:00 AM – 6:00 PM (Everyday Open)",
  googleMapsEmbed: "https://maps.app.goo.gl/dG5WWYBCotRQzvRJA",
  googleBusinessProfile: "https://share.google/HhXvqWDkefZ5bzNdL",
  reviewCount: 500,
  reviewRating: 4.9,

  navItems: [
    { label: "Home", href: "/" },
    { label: "Services", href: "/services" },
    { label: "Gallery", href: "/gallery" },
    { label: "About", href: "/about" },
    { label: "FAQ", href: "/faq" },
    { label: "Contact", href: "/contact" },
  ],

  areas: [
    "Kuala Lumpur", "Cheras", "Ampang", "Setapak", "Wangsa Maju",
    "Kepong", "Sri Petaling", "Bukit Jalil", "Mont Kiara", "Bangsar",
    "Desa ParkCity", "Taman Melawati", "Hulu Kelang",
    "Petaling Jaya", "Subang Jaya", "Shah Alam", "Puchong", "Damansara",
    "Kota Damansara", "Ara Damansara", "Sunway", "USJ", "Bandar Utama", "SS2",
    "Klang", "Port Klang", "Bukit Tinggi", "Setia Alam", "Meru",
    "Kota Kemuning", "Bukit Jelutong", "Glenmarie",
    "Batu Caves", "Selayang", "Rawang", "Kundang", "Sungai Buloh",
    "Kajang", "Bangi", "Semenyih", "Balakong", "Seri Kembangan", "Pandan Indah",
    "Bandar Puteri", "Putrajaya", "Cyberjaya", "Dengkil",
    "Selangor", "Sentul", "Bandar Botanic",
  ],

  areaPages: [
    {
      slug: "petaling-jaya",
      name: "Petaling Jaya",
      shortName: "PJ",
      state: "Selangor",
      lat: 3.10726,
      lng: 101.60671,
      population: "600,000+",
      landmarks: ["SS2", "Damansara Utama", "Tropicana", "Kelana Jaya", "Ara Damansara", "Taman Jaya"],
      description: "Aircond service Petaling Jaya (PJ) — KL Renovator dispatches trained HVAC technicians to all PJ zones including SS2, Damansara Utama, Tropicana, Kelana Jaya and Ara Damansara. Same-day booking available.",
      metaTitle: "Aircond Service Petaling Jaya (PJ) | KL Renovator — From RM 99",
      metaDesc: "Professional aircond servicing in Petaling Jaya. Chemical wash, overhaul, gas top-up, repairs. All brands. Same-day available. Call +60182983573.",
    },
    {
      slug: "cheras",
      name: "Cheras",
      shortName: "Cheras",
      state: "Kuala Lumpur / Selangor",
      lat: 3.08452,
      lng: 101.73421,
      population: "400,000+",
      landmarks: ["Taman Connaught", "Batu 9", "Batu 11", "Miharja", "Maluri", "Taman Mutiara"],
      description: "Aircond service Cheras — KL Renovator covers all Cheras zones including Taman Connaught, Batu 9, Batu 11, Miharja and Maluri. Fast response, transparent pricing, all brands supported.",
      metaTitle: "Aircond Service Cheras KL | KL Renovator — Chemical Wash From RM 120",
      metaDesc: "Expert aircond servicing in Cheras. Chemical wash, overhaul, gas top-up & repairs for all brands. Same-day available. Call +60182983573.",
    },
    {
      slug: "shah-alam",
      name: "Shah Alam",
      shortName: "Shah Alam",
      state: "Selangor",
      lat: 3.08507,
      lng: 101.53281,
      population: "700,000+",
      landmarks: ["Section 7", "Section 13", "Section 17", "Setia Alam", "Kota Kemuning", "Bukit Jelutong"],
      description: "Aircond service Shah Alam — KL Renovator services all Shah Alam sections including Section 7, 13, 17, Setia Alam, Kota Kemuning and Bukit Jelutong. Professional HVAC technicians, same-day slots.",
      metaTitle: "Aircond Service Shah Alam | KL Renovator — Same-Day Available",
      metaDesc: "Professional aircond servicing in Shah Alam. All sections covered. Chemical wash, overhaul, installations & repairs. Call +60182983573.",
    },
    {
      slug: "subang-jaya",
      name: "Subang Jaya",
      shortName: "Subang",
      state: "Selangor",
      lat: 3.05018,
      lng: 101.58983,
      population: "700,000+",
      landmarks: ["USJ", "SS15", "SS16", "Taipan", "Sunway", "Putra Heights"],
      description: "Aircond service Subang Jaya — KL Renovator covers USJ, SS15, SS16, Taipan, Sunway and Putra Heights. Expert chemical wash, overhaul, gas top-up and repairs for all major brands.",
      metaTitle: "Aircond Service Subang Jaya & USJ | KL Renovator — From RM 99",
      metaDesc: "Expert aircond service in Subang Jaya & USJ. Chemical wash, overhaul, gas top-up for Daikin, Panasonic, Mitsubishi & more. Call +60182983573.",
    },
    {
      slug: "ampang",
      name: "Ampang",
      shortName: "Ampang",
      state: "Selangor / KL",
      lat: 3.14778,
      lng: 101.76267,
      population: "300,000+",
      landmarks: ["Ampang Jaya", "Taman Muda", "Ukay Perdana", "Pandan Indah", "Taman Keramat"],
      description: "Aircond service Ampang — KL Renovator dispatches to Ampang Jaya, Taman Muda, Ukay Perdana, Pandan Indah and Taman Keramat. Fast response, honest pricing, no hidden charges.",
      metaTitle: "Aircond Service Ampang | KL Renovator — Fast Response, No Hidden Fees",
      metaDesc: "Professional aircond servicing in Ampang & Ampang Jaya. Chemical wash, overhaul, repairs & installations. Call +60182983573.",
    },
    {
      slug: "puchong",
      name: "Puchong",
      shortName: "Puchong",
      state: "Selangor",
      lat: 3.02726,
      lng: 101.61811,
      population: "300,000+",
      landmarks: ["IOI Mall", "Bandar Puteri", "Puchong Jaya", "Bukit Puchong", "Taman Wawasan"],
      description: "Aircond service Puchong — KL Renovator covers Bandar Puteri, Puchong Jaya, Bukit Puchong and Taman Wawasan. Expert HVAC technicians, same-day service, transparent pricing.",
      metaTitle: "Aircond Service Puchong | KL Renovator — Expert HVAC From RM 99",
      metaDesc: "Trusted aircond service in Puchong. Chemical wash, gas top-up, overhaul & repairs for all brands. Same-day available. Call +60182983573.",
    },
    {
      slug: "klang",
      name: "Klang",
      shortName: "Klang",
      state: "Selangor",
      lat: 3.04465,
      lng: 101.44694,
      population: "400,000+",
      landmarks: ["Bukit Tinggi", "Bandar Baru Klang", "Meru", "Port Klang", "Pandamaran", "Setia Alam"],
      description: "Aircond service Klang — KL Renovator services Bukit Tinggi, Bandar Baru Klang, Meru, Port Klang, Setia Alam and Pandamaran. All brands serviced, competitive rates, 1-month warranty.",
      metaTitle: "Aircond Service Klang | KL Renovator — All Brands, Transparent Pricing",
      metaDesc: "Professional aircond service in Klang. Bukit Tinggi, Meru, Port Klang, Setia Alam covered. Chemical wash, repairs & installations. Call +60182983573.",
    },
    {
      slug: "kajang",
      name: "Kajang",
      shortName: "Kajang",
      state: "Selangor",
      lat: 2.99330,
      lng: 101.78820,
      population: "250,000+",
      landmarks: ["Bangi", "Semenyih", "Cheras Baru", "Taman Kajang Maju", "Sungai Chua", "Balakong"],
      description: "Aircond service Kajang — KL Renovator covers Kajang, Bangi, Semenyih, Balakong and surrounding areas. Expert aircond chemical wash, overhaul, gas top-up and repairs for all brands.",
      metaTitle: "Aircond Service Kajang & Bangi | KL Renovator — Same-Day Service",
      metaDesc: "Expert aircond servicing in Kajang and Bangi. Chemical wash, overhaul & repairs for all brands. Fast response. Call +60182983573.",
    },
    {
      slug: "batu-caves",
      name: "Batu Caves",
      shortName: "Batu Caves",
      state: "Selangor",
      lat: 3.23726,
      lng: 101.68316,
      population: "200,000+",
      landmarks: ["Taman Batu Muda", "Sri Murugan", "Taman Selayang", "Kepong Baru", "Rawang"],
      description: "Aircond service Batu Caves — KL Renovator covers Batu Caves, Taman Batu Muda, Taman Selayang, Kepong Baru and Rawang. Professional HVAC team, same-day slots, honest pricing.",
      metaTitle: "Aircond Service Batu Caves | KL Renovator — Professional HVAC Team",
      metaDesc: "Professional aircond servicing in Batu Caves & Selayang. Chemical wash, overhaul & repairs. All brands. Call +60182983573.",
    },
    {
      slug: "damansara",
      name: "Damansara",
      shortName: "Damansara",
      state: "Selangor / KL",
      lat: 3.15283,
      lng: 101.61278,
      population: "300,000+",
      landmarks: ["Damansara Perdana", "Damansara Damai", "Kota Damansara", "Mutiara Damansara", "Ara Damansara", "One Utama"],
      description: "Aircond service Damansara — KL Renovator covers Damansara Perdana, Damansara Damai, Kota Damansara, Ara Damansara and Mutiara Damansara. Expert servicing for condominiums and landed homes.",
      metaTitle: "Aircond Service Damansara | KL Renovator — Condo & Landed Specialists",
      metaDesc: "Expert aircond service in Damansara. All zones covered including Kota Damansara & Ara Damansara. Chemical wash, overhaul, gas top-up. Call +60182983573.",
    },
    {
      slug: "bangsar",
      name: "Bangsar",
      shortName: "Bangsar",
      state: "Kuala Lumpur",
      lat: 3.12897,
      lng: 101.67434,
      population: "150,000+",
      landmarks: ["Bangsar Baru", "Bangsar South", "Kerinchi", "Pantai Dalam", "Mid Valley"],
      description: "Aircond service Bangsar — KL Renovator covers Bangsar Baru, Bangsar South, Kerinchi and Pantai Dalam. Professional HVAC service for condominiums, apartments and offices.",
      metaTitle: "Aircond Service Bangsar KL | KL Renovator — Condo Specialist",
      metaDesc: "Professional aircond servicing in Bangsar & Bangsar South. Chemical wash, overhaul & repairs. All brands. Call +60182983573.",
    },
    {
      slug: "mont-kiara",
      name: "Mont Kiara",
      shortName: "Mont Kiara",
      state: "Kuala Lumpur",
      lat: 3.17278,
      lng: 101.64876,
      population: "100,000+",
      landmarks: ["Sri Hartamas", "Solaris Dutamas", "Duta Nusantara", "Plaza Mont Kiara"],
      description: "Aircond service Mont Kiara — KL Renovator provides professional HVAC servicing for condominiums and luxury properties in Mont Kiara, Sri Hartamas and Solaris Dutamas.",
      metaTitle: "Aircond Service Mont Kiara | KL Renovator — Luxury Condo Specialist",
      metaDesc: "Professional aircond servicing in Mont Kiara & Sri Hartamas. Chemical wash, overhaul & repairs for condos. Call +60182983573.",
    },
    {
      slug: "setapak",
      name: "Setapak",
      shortName: "Setapak",
      state: "Kuala Lumpur",
      lat: 3.19383,
      lng: 101.71247,
      population: "200,000+",
      landmarks: ["Taman Setapak", "Wangsa Maju", "Gombak", "Taman Sri Rampai"],
      description: "Aircond service Setapak & Wangsa Maju — KL Renovator covers Setapak, Wangsa Maju, Taman Sri Rampai and surrounding areas. Fast response, transparent pricing, all brands serviced.",
      metaTitle: "Aircond Service Setapak & Wangsa Maju | KL Renovator",
      metaDesc: "Expert aircond service in Setapak & Wangsa Maju. Chemical wash, overhaul & repairs. Fast response. Call +60182983573.",
    },
    {
      slug: "sentul",
      name: "Sentul",
      shortName: "Sentul",
      state: "Kuala Lumpur",
      lat: 3.18162,
      lng: 101.68923,
      population: "150,000+",
      landmarks: ["Sentul Park", "Jalan Ipoh", "Taman Wahyu", "Brickfields"],
      description: "Aircond service Sentul — KL Renovator covers Sentul, Taman Wahyu, Jalan Ipoh corridor and surrounding areas. Professional HVAC team with same-day slots available.",
      metaTitle: "Aircond Service Sentul KL | KL Renovator — Same-Day Slots",
      metaDesc: "Professional aircond servicing in Sentul KL. Chemical wash, overhaul & repairs for all brands. Same-day available. Call +60182983573.",
    },
    {
      slug: "selayang",
      name: "Selayang",
      shortName: "Selayang",
      state: "Selangor",
      lat: 3.22050,
      lng: 101.64120,
      population: "250,000+",
      landmarks: ["Selayang Mall", "Batu Caves", "Taman Selayang Baru", "Gombak", "Rawang"],
      description: "Aircond service Selayang — KL Renovator is headquartered in Selayang, providing ultra-fast HVAC response across Selayang Baru, Gombak and all surrounding zones.",
      metaTitle: "Aircond Service Selayang | KL Renovator — Headquartered Here",
      metaDesc: "KL Renovator is based in Selayang. Expert aircond chemical wash, overhaul, gas top-up & repairs. Fastest response. Call +60182983573.",
    },
    {
      slug: "putrajaya",
      name: "Putrajaya",
      shortName: "Putrajaya",
      state: "Putrajaya",
      lat: 2.92636,
      lng: 101.69625,
      population: "100,000+",
      landmarks: ["Presinct 1", "Presinct 9", "Presinct 14", "Presinct 18", "Cyberjaya", "Dengkil"],
      description: "Aircond service Putrajaya — KL Renovator covers all Putrajaya precincts and nearby Dengkil. Professional HVAC team for government quarters, condos and commercial buildings.",
      metaTitle: "Aircond Service Putrajaya | KL Renovator — All Precincts Covered",
      metaDesc: "Professional aircond servicing in Putrajaya. All precincts covered. Chemical wash, overhaul & repairs. Call +60182983573.",
    },
    {
      slug: "cyberjaya",
      name: "Cyberjaya",
      shortName: "Cyberjaya",
      state: "Selangor",
      lat: 2.92160,
      lng: 101.65348,
      population: "80,000+",
      landmarks: ["Shaftsbury", "Tamarind Square", "Cyberia", "Jade Hills", "Kotaray"],
      description: "Aircond service Cyberjaya — KL Renovator provides professional HVAC servicing for tech parks, condominiums and offices in Cyberjaya including Shaftsbury, Cyberia and Tamarind Square.",
      metaTitle: "Aircond Service Cyberjaya | KL Renovator — Tech Hub HVAC Specialist",
      metaDesc: "Expert aircond servicing in Cyberjaya. Chemical wash, overhaul & repairs for condos and offices. All brands. Call +60182983573.",
    },
    {
      slug: "kepong",
      name: "Kepong",
      shortName: "Kepong",
      state: "Kuala Lumpur",
      lat: 3.20750,
      lng: 101.63590,
      population: "200,000+",
      landmarks: ["Kepong Baru", "Metro Prima", "Sri Damansara", "Desa Jaya", "Taman Ehsan"],
      description: "Aircond service Kepong — KL Renovator covers Kepong Baru, Metro Prima, Sri Damansara, Desa Jaya and Taman Ehsan. Fast response, transparent pricing, all brands serviced.",
      metaTitle: "Aircond Service Kepong KL | KL Renovator — Same-Day Available",
      metaDesc: "Expert aircond servicing in Kepong. Chemical wash, overhaul & repairs for all brands. Same-day slots available. Call +60182983573.",
    },
    {
      slug: "sri-petaling",
      name: "Sri Petaling",
      shortName: "Sri Petaling",
      state: "Kuala Lumpur",
      lat: 3.07520,
      lng: 101.69430,
      population: "150,000+",
      landmarks: ["Bukit Jalil", "OUG", "Taman Desa", "Kuchai Lama", "Salak South"],
      description: "Aircond service Sri Petaling & Bukit Jalil — KL Renovator covers Sri Petaling, Bukit Jalil, OUG, Taman Desa and Kuchai Lama. Professional HVAC team, honest pricing.",
      metaTitle: "Aircond Service Sri Petaling & Bukit Jalil | KL Renovator",
      metaDesc: "Professional aircond servicing in Sri Petaling & Bukit Jalil. Chemical wash, overhaul & repairs. All brands. Call +60182983573.",
    },
    {
      slug: "sunway",
      name: "Sunway",
      shortName: "Sunway",
      state: "Selangor",
      lat: 3.06830,
      lng: 101.60340,
      population: "120,000+",
      landmarks: ["Sunway Pyramid", "Sunway Velocity", "Bandar Sunway", "USJ", "Putra Heights"],
      description: "Aircond service Sunway & USJ — KL Renovator covers Bandar Sunway, USJ, Putra Heights and all surrounding areas. Expert HVAC team, same-day service.",
      metaTitle: "Aircond Service Sunway & USJ | KL Renovator — From RM 99",
      metaDesc: "Trusted aircond service in Sunway & USJ. Chemical wash, overhaul & repairs for all brands. Same-day slots. Call +60182983573.",
    },
    {
      slug: "rawang",
      name: "Rawang",
      shortName: "Rawang",
      state: "Selangor",
      lat: 3.31890,
      lng: 101.57690,
      population: "150,000+",
      landmarks: ["Taman Rawang Perdana", "Kundang", "Bandar Country Homes", "Serendah"],
      description: "Aircond service Rawang & Kundang — KL Renovator covers Rawang, Kundang, Bandar Country Homes and surrounding areas. Professional HVAC team with fast response.",
      metaTitle: "Aircond Service Rawang & Kundang | KL Renovator",
      metaDesc: "Expert aircond servicing in Rawang & Kundang. Chemical wash, overhaul & repairs for all brands. Call +60182983573.",
    },
    {
      slug: "kajang-semenyih",
      name: "Semenyih",
      shortName: "Semenyih",
      state: "Selangor",
      lat: 2.94300,
      lng: 101.84520,
      population: "100,000+",
      landmarks: ["Semenyih Town", "Taman Pelangi", "Kajang South", "Bangi Lama"],
      description: "Aircond service Semenyih — KL Renovator covers Semenyih, Kajang South and surrounding areas. Expert aircond chemical wash, overhaul and repairs for all brands.",
      metaTitle: "Aircond Service Semenyih | KL Renovator — Professional HVAC",
      metaDesc: "Professional aircond servicing in Semenyih. Chemical wash, overhaul & repairs. All brands. Call +60182983573.",
    },
    {
      slug: "seri-kembangan",
      name: "Seri Kembangan",
      shortName: "Seri Kembangan",
      state: "Selangor",
      lat: 3.01640,
      lng: 101.70900,
      population: "120,000+",
      landmarks: ["Balakong", "Pandan Indah", "Taman Equine", "Serdang"],
      description: "Aircond service Seri Kembangan & Balakong — KL Renovator covers Seri Kembangan, Balakong, Pandan Indah and Taman Equine. Fast response, all brands serviced.",
      metaTitle: "Aircond Service Seri Kembangan & Balakong | KL Renovator",
      metaDesc: "Expert aircond servicing in Seri Kembangan & Balakong. Chemical wash, overhaul & repairs. Call +60182983573.",
    },
    {
      slug: "desa-parkcity",
      name: "Desa ParkCity",
      shortName: "Desa ParkCity",
      state: "Kuala Lumpur",
      lat: 3.18590,
      lng: 101.62800,
      population: "50,000+",
      landmarks: ["The Waterfront", "Kepong", "Sri Damansara", "Desa ParkCity Central Park"],
      description: "Aircond service Desa ParkCity — KL Renovator provides premium HVAC servicing for condominiums and landed homes in Desa ParkCity, one of KL's most prestigious residential townships.",
      metaTitle: "Aircond Service Desa ParkCity KL | KL Renovator — Premium Condo Specialist",
      metaDesc: "Professional aircond servicing in Desa ParkCity KL. Chemical wash, overhaul & repairs for condos and landed homes. Call +60182983573.",
    },
    {
      slug: "taman-melawati",
      name: "Taman Melawati",
      shortName: "Taman Melawati",
      state: "Kuala Lumpur",
      lat: 3.21800,
      lng: 101.74900,
      population: "120,000+",
      landmarks: ["Melawati Mall", "Taman Melawati Square", "Hulu Kelang", "Ampang Jaya"],
      description: "Aircond service Taman Melawati — KL Renovator covers Taman Melawati, Melawati Mall area, and Hulu Kelang corridor. Fast response, honest pricing, experienced technicians.",
      metaTitle: "Aircond Service Taman Melawati KL | KL Renovator — Same-Day Available",
      metaDesc: "Expert aircond service in Taman Melawati & Hulu Kelang. Chemical wash, overhaul, gas top-up & repairs. Call +60182983573.",
    },
    {
      slug: "hulu-kelang",
      name: "Hulu Kelang",
      shortName: "Hulu Kelang",
      state: "Selangor",
      lat: 3.20500,
      lng: 101.75800,
      population: "80,000+",
      landmarks: ["Taman Keramat", "Ukay Perdana", "Taman Melawati", "Taman AU"],
      description: "Aircond service Hulu Kelang — KL Renovator dispatches to Hulu Kelang, Ukay Perdana, Taman Keramat and all nearby residential areas. Professional HVAC, same-day slots.",
      metaTitle: "Aircond Service Hulu Kelang | KL Renovator — Professional HVAC",
      metaDesc: "Professional aircond servicing in Hulu Kelang. Chemical wash, overhaul & repairs for all brands. Fast response. Call +60182983573.",
    },
    {
      slug: "bandar-puteri",
      name: "Bandar Puteri",
      shortName: "Bandar Puteri",
      state: "Selangor",
      lat: 3.00500,
      lng: 101.61800,
      population: "80,000+",
      landmarks: ["Puchong", "IOI City Mall", "Bukit Puchong", "Putra Heights"],
      description: "Aircond service Bandar Puteri Puchong — KL Renovator covers Bandar Puteri, Puchong IOI area and surrounding zones. Expert HVAC team, transparent pricing, all brands serviced.",
      metaTitle: "Aircond Service Bandar Puteri Puchong | KL Renovator",
      metaDesc: "Expert aircond service in Bandar Puteri Puchong. Chemical wash, gas top-up, overhaul & repairs. Same-day slots. Call +60182983573.",
    },
    {
      slug: "bandar-botanic",
      name: "Bandar Botanic",
      shortName: "Bandar Botanic",
      state: "Selangor",
      lat: 3.00200,
      lng: 101.42500,
      population: "60,000+",
      landmarks: ["Klang", "Botanic Golf Course", "Taman Sri Muda", "Kota Kemuning"],
      description: "Aircond service Bandar Botanic Klang — KL Renovator services Bandar Botanic and surrounding Klang areas. Professional aircond chemical wash, overhaul, gas top-up and repairs.",
      metaTitle: "Aircond Service Bandar Botanic Klang | KL Renovator",
      metaDesc: "Professional aircond servicing in Bandar Botanic Klang. Chemical wash, overhaul & repairs. All brands. Call +60182983573.",
    },
    {
      slug: "glenmarie",
      name: "Glenmarie",
      shortName: "Glenmarie",
      state: "Selangor",
      lat: 3.09200,
      lng: 101.54500,
      population: "50,000+",
      landmarks: ["Shah Alam", "Subang Airport", "Ara Damansara", "HICOM Glenmarie"],
      description: "Aircond service Glenmarie Shah Alam — KL Renovator covers Glenmarie industrial and residential areas, nearby Subang and HICOM zones. Expert HVAC servicing for commercial and residential units.",
      metaTitle: "Aircond Service Glenmarie Shah Alam | KL Renovator",
      metaDesc: "Expert aircond service in Glenmarie. Industrial & residential units. Chemical wash, overhaul & repairs. All brands. Call +60182983573.",
    },
    {
      slug: "kota-kemuning",
      name: "Kota Kemuning",
      shortName: "Kota Kemuning",
      state: "Selangor",
      lat: 3.01800,
      lng: 101.49800,
      population: "80,000+",
      landmarks: ["Shah Alam", "Telok Panglima Garang", "Bukit Jelutong", "Kemuning Utama"],
      description: "Aircond service Kota Kemuning — KL Renovator covers Kota Kemuning, Bukit Jelutong and surrounding Shah Alam areas. Professional HVAC technicians, honest pricing, all brands serviced.",
      metaTitle: "Aircond Service Kota Kemuning Shah Alam | KL Renovator",
      metaDesc: "Professional aircond servicing in Kota Kemuning & Bukit Jelutong. Chemical wash, overhaul & repairs. Call +60182983573.",
    },
    {
      slug: "bukit-jelutong",
      name: "Bukit Jelutong",
      shortName: "Bukit Jelutong",
      state: "Selangor",
      lat: 3.09500,
      lng: 101.51500,
      population: "70,000+",
      landmarks: ["Shah Alam", "Kota Kemuning", "Glenmarie", "PKNS Bukit Jelutong"],
      description: "Aircond service Bukit Jelutong — KL Renovator services Bukit Jelutong residents and businesses with professional HVAC solutions including chemical wash, overhaul, gas top-up and repairs.",
      metaTitle: "Aircond Service Bukit Jelutong Shah Alam | KL Renovator",
      metaDesc: "Expert aircond servicing in Bukit Jelutong Shah Alam. Chemical wash, overhaul & repairs. All brands. Same-day available. Call +60182983573.",
    },
    {
      slug: "setia-alam",
      name: "Setia Alam",
      shortName: "Setia Alam",
      state: "Selangor",
      lat: 3.09600,
      lng: 101.46200,
      population: "100,000+",
      landmarks: ["Shah Alam", "Klang", "Setia City Mall", "Eco Ardence"],
      description: "Aircond service Setia Alam — KL Renovator covers Setia Alam township, Setia City Mall area and surrounding Klang/Shah Alam zones. Expert HVAC team, same-day slots available.",
      metaTitle: "Aircond Service Setia Alam | KL Renovator — Shah Alam & Klang",
      metaDesc: "Professional aircond servicing in Setia Alam. Chemical wash, overhaul, gas top-up & repairs. All brands. Call +60182983573.",
    },
    {
      slug: "ss2",
      name: "SS2",
      shortName: "SS2",
      state: "Selangor",
      lat: 3.11800,
      lng: 101.62200,
      population: "60,000+",
      landmarks: ["Petaling Jaya", "SS2 Pasar Malam", "Damansara Utama", "Kelana Jaya"],
      description: "Aircond service SS2 Petaling Jaya — KL Renovator covers SS2 and all surrounding Petaling Jaya zones. Professional aircond chemical wash, overhaul, gas top-up and repairs for all brands.",
      metaTitle: "Aircond Service SS2 Petaling Jaya | KL Renovator",
      metaDesc: "Expert aircond service in SS2 PJ. Chemical wash, overhaul & repairs for all brands. Fast response. Call +60182983573.",
    },
    {
      slug: "ara-damansara",
      name: "Ara Damansara",
      shortName: "Ara Damansara",
      state: "Selangor",
      lat: 3.12400,
      lng: 101.58600,
      population: "80,000+",
      landmarks: ["Subang Jaya", "Petaling Jaya", "Oasis Ara Damansara", "Glenmarie"],
      description: "Aircond service Ara Damansara — KL Renovator dispatches to Ara Damansara, Oasis Square and surrounding PJ/Subang corridor. Expert HVAC servicing for condominiums and landed homes.",
      metaTitle: "Aircond Service Ara Damansara PJ | KL Renovator — Condo Specialist",
      metaDesc: "Professional aircond servicing in Ara Damansara. Chemical wash, overhaul & repairs for condos and homes. All brands. Call +60182983573.",
    },
    {
      slug: "bandar-utama",
      name: "Bandar Utama",
      shortName: "Bandar Utama",
      state: "Selangor",
      lat: 3.15400,
      lng: 101.61100,
      population: "100,000+",
      landmarks: ["One Utama Shopping Centre", "Damansara", "Tropicana", "Petaling Jaya"],
      description: "Aircond service Bandar Utama — KL Renovator covers Bandar Utama, One Utama area and surrounding Damansara zones. Professional HVAC team, transparent pricing, all brands supported.",
      metaTitle: "Aircond Service Bandar Utama PJ | KL Renovator — All Brands",
      metaDesc: "Expert aircond servicing in Bandar Utama & One Utama area. Chemical wash, overhaul & repairs. Same-day available. Call +60182983573.",
    },
    {
      slug: "sungai-buloh",
      name: "Sungai Buloh",
      shortName: "Sungai Buloh",
      state: "Selangor",
      lat: 3.20700,
      lng: 101.57900,
      population: "150,000+",
      landmarks: ["Kota Damansara", "Rawang", "Kepong", "Elmina"],
      description: "Aircond service Sungai Buloh — KL Renovator covers Sungai Buloh, Elmina, and surrounding northern Selangor areas. Fast response, expert HVAC technicians, all brands serviced.",
      metaTitle: "Aircond Service Sungai Buloh | KL Renovator — Fast Response",
      metaDesc: "Professional aircond servicing in Sungai Buloh. Chemical wash, overhaul & repairs for all brands. Same-day available. Call +60182983573.",
    },
    {
      slug: "wangsa-maju",
      name: "Wangsa Maju",
      shortName: "Wangsa Maju",
      state: "Kuala Lumpur",
      lat: 3.19800,
      lng: 101.72400,
      population: "180,000+",
      landmarks: ["Setapak", "Wangsa Walk Mall", "Taman Sri Rampai", "Gombak"],
      description: "Aircond service Wangsa Maju — KL Renovator covers Wangsa Maju, Wangsa Walk area, Taman Sri Rampai and surrounding Setapak zones. Same-day service, transparent pricing.",
      metaTitle: "Aircond Service Wangsa Maju KL | KL Renovator — Same-Day",
      metaDesc: "Expert aircond service in Wangsa Maju. Chemical wash, overhaul, gas top-up & repairs. All brands. Fast response. Call +60182983573.",
    },
    {
      slug: "balakong",
      name: "Balakong",
      shortName: "Balakong",
      state: "Selangor",
      lat: 3.04200,
      lng: 101.75600,
      population: "80,000+",
      landmarks: ["Seri Kembangan", "Cheras", "Taman Len Seng", "Pandan Indah"],
      description: "Aircond service Balakong — KL Renovator covers Balakong industrial and residential areas, Seri Kembangan and nearby Cheras zones. Professional HVAC, same-day slots available.",
      metaTitle: "Aircond Service Balakong Selangor | KL Renovator",
      metaDesc: "Expert aircond servicing in Balakong. Chemical wash, overhaul & repairs for all brands. Same-day slots. Call +60182983573.",
    },
  ],

  brandPages: [
    {
      slug: "daikin",
      name: "Daikin",
      metaTitle: "Daikin Aircond Service KL & Selangor | KL Renovator",
      metaDesc: "Expert Daikin aircond servicing in KL & Selangor. Chemical wash, gas top-up, repairs & installations for all Daikin models. Call +60182983573.",
      description: "KL Renovator technicians are experienced in servicing all Daikin air conditioner models across Kuala Lumpur and Selangor, including wall-mounted, ceiling cassette and multi-split systems.",
      models: ["Daikin iSmile Series", "Daikin SMILE Series", "Daikin FTKF", "Daikin FTKM", "Daikin SkyAir", "Daikin VRV"],
      gasTypes: ["R32", "R410A"],
    },
    {
      slug: "panasonic",
      name: "Panasonic",
      metaTitle: "Panasonic Aircond Service KL & Selangor | KL Renovator",
      metaDesc: "Expert Panasonic aircond servicing in KL & Selangor. Chemical wash, gas top-up, repairs & installations for all Panasonic models. Call +60182983573.",
      description: "KL Renovator technicians are experienced in servicing all Panasonic air conditioner models across KL and Selangor, including the popular PU/CS series and inverter models.",
      models: ["Panasonic CS-PU Series", "Panasonic CS-YU Series", "Panasonic Nanoe-X", "Panasonic Econavi", "Panasonic Multi-Split"],
      gasTypes: ["R32", "R410A"],
    },
    {
      slug: "mitsubishi",
      name: "Mitsubishi Electric",
      metaTitle: "Mitsubishi Electric Aircond Service KL & Selangor | KL Renovator",
      metaDesc: "Expert Mitsubishi Electric aircond servicing in KL & Selangor. Chemical wash, gas top-up, repairs for all Mitsubishi models. Call +60182983573.",
      description: "KL Renovator technicians are experienced in servicing Mitsubishi Electric air conditioners including the MSY series, MXY multi-split and City Multi VRF systems.",
      models: ["Mitsubishi MSY Series", "Mitsubishi MXY Multi-Split", "Mitsubishi City Multi VRF", "Mitsubishi MFZ Floor Standing"],
      gasTypes: ["R32", "R410A"],
    },
    {
      slug: "york",
      name: "York",
      metaTitle: "York Aircond Service KL & Selangor | KL Renovator",
      metaDesc: "Expert York aircond servicing in KL & Selangor. Chemical wash, gas top-up, repairs & installations for all York models. Call +60182983573.",
      description: "KL Renovator technicians are experienced in servicing York air conditioner models across KL and Selangor, including residential and light commercial units.",
      models: ["York YHJF Series", "York YHAF Series", "York Affinity", "York Multi-Zone"],
      gasTypes: ["R32", "R410A", "R22"],
    },
    {
      slug: "acson",
      name: "Acson",
      metaTitle: "Acson Aircond Service KL & Selangor | KL Renovator",
      metaDesc: "Expert Acson aircond servicing in KL & Selangor. Chemical wash, gas top-up, repairs & installations for all Acson models. Call +60182983573.",
      description: "KL Renovator technicians are experienced in servicing Acson air conditioners, a trusted Malaysian brand with a wide installed base across Klang Valley homes and offices.",
      models: ["Acson R32 Inverter", "Acson A5WM Series", "Acson Ceiling Cassette", "Acson Multi-Split"],
      gasTypes: ["R32", "R410A"],
    },
    {
      slug: "carrier",
      name: "Carrier",
      metaTitle: "Carrier Aircond Service KL & Selangor | KL Renovator",
      metaDesc: "Expert Carrier aircond servicing in KL & Selangor. Chemical wash, gas top-up, repairs & installations for all Carrier models. Call +60182983573.",
      description: "KL Renovator technicians are experienced in servicing Carrier air conditioner systems, including commercial ceiling cassettes and residential wall-mounted units across KL and Selangor.",
      models: ["Carrier Xpression", "Carrier Performance Series", "Carrier 40QAC Ceiling Cassette"],
      gasTypes: ["R32", "R410A", "R22"],
    },
    {
      slug: "midea",
      name: "Midea",
      metaTitle: "Midea Aircond Service KL & Selangor | KL Renovator",
      metaDesc: "Expert Midea aircond servicing in KL & Selangor. Chemical wash, gas top-up, repairs & installations for all Midea models. Call +60182983573.",
      description: "KL Renovator technicians are experienced in servicing Midea air conditioners including the popular Xtreme Save and Xtreme Cool series widely used in Klang Valley homes.",
      models: ["Midea Xtreme Save", "Midea Xtreme Cool", "Midea U-Shape Inverter", "Midea Ceiling Cassette"],
      gasTypes: ["R32", "R410A"],
    },
    {
      slug: "haier",
      name: "Haier",
      metaTitle: "Haier Aircond Service KL & Selangor | KL Renovator",
      metaDesc: "Expert Haier aircond servicing in KL & Selangor. Chemical wash, gas top-up, repairs & installations for all Haier models. Call +60182983573.",
      description: "KL Renovator technicians are experienced in servicing Haier air conditioners across KL and Selangor, covering wall-mounted inverter and non-inverter residential models.",
      models: ["Haier Nebula Series", "Haier Flexis", "Haier Big Freeze", "Haier Multi-Split"],
      gasTypes: ["R32", "R410A"],
    },
    {
      slug: "toshiba",
      name: "Toshiba",
      metaTitle: "Toshiba Aircond Service KL & Selangor | KL Renovator",
      metaDesc: "Expert Toshiba aircond servicing in KL & Selangor. Chemical wash, gas top-up, repairs & installations for all Toshiba models. Call +60182983573.",
      description: "KL Renovator technicians are experienced in servicing Toshiba air conditioners including residential and light commercial units across Kuala Lumpur and Selangor.",
      models: ["Toshiba RAS Series", "Toshiba Seiya", "Toshiba Shorai Edge", "Toshiba Ceiling Cassette"],
      gasTypes: ["R32", "R410A"],
    },
    {
      slug: "hitachi",
      name: "Hitachi",
      metaTitle: "Hitachi Aircond Service KL & Selangor | KL Renovator",
      metaDesc: "Expert Hitachi aircond servicing in KL & Selangor. Chemical wash, gas top-up, repairs & installations for all Hitachi models. Call +60182983573.",
      description: "KL Renovator technicians are experienced in servicing Hitachi air conditioners including the popular Frost Wash and Ecosmart series across KL and Selangor.",
      models: ["Hitachi Frost Wash", "Hitachi Ecosmart", "Hitachi Performance Series", "Hitachi iSense"],
      gasTypes: ["R32", "R410A"],
    },
    {
      slug: "samsung",
      name: "Samsung",
      metaTitle: "Samsung Aircond Service KL & Selangor | KL Renovator",
      metaDesc: "Expert Samsung aircond servicing in KL & Selangor. Chemical wash, gas top-up, repairs & installations for all Samsung models. Call +60182983573.",
      description: "KL Renovator technicians are experienced in servicing Samsung air conditioners including the WindFree, Triangle and Boracay series across KL and Selangor.",
      models: ["Samsung WindFree", "Samsung Triangle Series", "Samsung Boracay", "Samsung DVM Multi-Split"],
      gasTypes: ["R32", "R410A"],
    },
    {
      slug: "lg",
      name: "LG",
      metaTitle: "LG Aircond Service KL & Selangor | KL Renovator",
      metaDesc: "Expert LG aircond servicing in KL & Selangor. Chemical wash, gas top-up, repairs & installations for all LG models. Call +60182983573.",
      description: "KL Renovator technicians are experienced in servicing LG air conditioners including the Dual Inverter, ArtCool and DUALCOOL series widely used across KL and Selangor homes.",
      models: ["LG Dual Inverter", "LG ArtCool", "LG DUALCOOL", "LG Multi F Max"],
      gasTypes: ["R32", "R410A"],
    },
    {
      slug: "sharp",
      name: "Sharp",
      metaTitle: "Sharp Aircond Service KL & Selangor | KL Renovator",
      metaDesc: "Expert Sharp aircond servicing in KL & Selangor. Chemical wash, gas top-up, repairs & installations for all Sharp models. Call +60182983573.",
      description: "KL Renovator technicians are experienced in servicing Sharp air conditioners including Plasmacluster and J-Tech Inverter series across KL and Selangor.",
      models: ["Sharp Plasmacluster", "Sharp J-Tech Inverter", "Sharp Standard Inverter", "Sharp Ceiling Cassette"],
      gasTypes: ["R32", "R410A"],
    },
    {
      slug: "fujitsu",
      name: "Fujitsu",
      metaTitle: "Fujitsu Aircond Service KL & Selangor | KL Renovator",
      metaDesc: "Expert Fujitsu aircond servicing in KL & Selangor. Chemical wash, gas top-up, repairs & installations for all Fujitsu models. Call +60182983573.",
      description: "KL Renovator technicians are experienced in servicing Fujitsu General air conditioners including residential and commercial HVAC systems across KL and Selangor.",
      models: ["Fujitsu Nocria Series", "Fujitsu AOYG Multi-Split", "Fujitsu ABTG Ceiling Cassette", "Fujitsu Halcyon"],
      gasTypes: ["R32", "R410A"],
    },
    {
      slug: "gree",
      name: "Gree",
      metaTitle: "Gree Aircond Service KL & Selangor | KL Renovator",
      metaDesc: "Expert Gree aircond servicing in KL & Selangor. Chemical wash, gas top-up, repairs & installations for all Gree models. Call +60182983573.",
      description: "KL Renovator technicians are experienced in servicing Gree air conditioners, one of the world's largest HVAC manufacturers, covering residential and commercial units across KL and Selangor.",
      models: ["Gree Fairy Series", "Gree Pular Series", "Gree Multi+ Series", "Gree Flexx"],
      gasTypes: ["R32", "R410A"],
    },
  ],

  problemPages: [
    { slug: "aircond-not-cold", name: "Aircond Not Cold", metaTitle: "Aircond Not Cold? Causes & Fix in KL & Selangor | KL Renovator", metaDesc: "Aircond running but not cold in KL or Selangor? Find out why and get it fixed fast. KL Renovator diagnoses and repairs all brands. Call +60182983573.", h1: "Aircond Not Cold — Causes & Repair in KL & Selangor", description: "If your aircond is running but not producing cold air, the most common causes are low refrigerant gas, a dirty evaporator coil, or a faulty capacitor. KL Renovator diagnoses and fixes all aircond cooling problems across KL and Selangor.", relatedService: "gas-topup" },
    { slug: "aircond-water-leaking", name: "Aircond Water Leaking", metaTitle: "Aircond Water Leaking? Fix It Fast in KL & Selangor | KL Renovator", metaDesc: "Aircond leaking water in KL or Selangor? Don't ignore it. Get it fixed today by KL Renovator. All brands, same-day service. Call +60182983573.", h1: "Aircond Water Leaking — Causes & Repair in KL & Selangor", description: "A leaking aircond indoor unit is usually caused by a blocked drain pipe or dirty drain pan. KL Renovator diagnoses and repairs all water leaking issues across KL and Selangor with same-day service.", relatedService: "chemical-overhaul" },
    { slug: "aircond-making-noise", name: "Aircond Making Noise", metaTitle: "Aircond Making Noise? Causes & Fix KL & Selangor | KL Renovator", metaDesc: "Aircond making loud noise in KL or Selangor? Rattling, buzzing or grinding sounds diagnosed and fixed. All brands. Call +60182983573.", h1: "Aircond Making Noise — Causes & Repair in KL & Selangor", description: "Unusual noises from your aircond — rattling, buzzing, or grinding — usually indicate a loose part, dirty fan blade, or failing fan motor. KL Renovator diagnoses and fixes all aircond noise problems.", relatedService: "repair" },
    { slug: "aircond-bad-smell", name: "Aircond Bad Smell", metaTitle: "Aircond Bad Smell? Fix Mould & Odour in KL & Selangor | KL Renovator", metaDesc: "Aircond blowing bad smell in KL or Selangor? Mould, bacteria and odour removed by chemical wash or overhaul. Call +60182983573.", h1: "Aircond Bad Smell — Mould & Odour Fix in KL & Selangor", description: "Bad smells from your aircond are caused by mould and bacteria buildup on the evaporator coil and blower wheel. A chemical wash or chemical overhaul by KL Renovator permanently removes the smell.", relatedService: "chemical-wash" },
    { slug: "aircond-freezing-up", name: "Aircond Freezing Up", metaTitle: "Aircond Freezing Up? Ice on Coil Fix KL & Selangor | KL Renovator", metaDesc: "Aircond coil freezing up in KL or Selangor? Ice formation caused by low gas or dirty coil. KL Renovator fixes it. Call +60182983573.", h1: "Aircond Freezing Up — Ice on Coil Repair in KL & Selangor", description: "Aircond ice formation is caused by low refrigerant gas or severely blocked evaporator coils. KL Renovator diagnoses the root cause and performs the correct service — gas top-up or chemical overhaul.", relatedService: "chemical-overhaul" },
    { slug: "aircond-low-gas", name: "Aircond Low Gas", metaTitle: "Aircond Low Gas Symptoms & Top-Up KL & Selangor | KL Renovator", metaDesc: "Signs your aircond has low gas in KL or Selangor. R22, R410A, R32 gas top-up from RM 120. Leak check included. Call +60182983573.", h1: "Aircond Low Gas — Symptoms & Gas Top-Up in KL & Selangor", description: "Low refrigerant gas causes warm air, longer cooling cycles, ice formation and high electricity bills. KL Renovator tops up R22, R410A and R32 gas with precision balancing and leak check included.", relatedService: "gas-topup" },
    { slug: "aircond-gas-leak", name: "Aircond Gas Leak", metaTitle: "Aircond Gas Leak Detection & Repair KL & Selangor | KL Renovator", metaDesc: "Aircond gas leak in KL or Selangor? KL Renovator detects leaks, repairs the pipe and tops up gas. R22, R410A, R32. Call +60182983573.", h1: "Aircond Gas Leak — Detection & Repair in KL & Selangor", description: "A gas leak causes repeated cooling failure even after top-ups. KL Renovator identifies the leak source, repairs the copper pipe or valve, then tops up the refrigerant to correct pressure.", relatedService: "gas-topup" },
    { slug: "aircond-compressor-problem", name: "Aircond Compressor Problem", metaTitle: "Aircond Compressor Problem & Repair KL & Selangor | KL Renovator", metaDesc: "Aircond compressor not working in KL or Selangor? KL Renovator diagnoses and repairs or replaces compressors for all brands. Call +60182983573.", h1: "Aircond Compressor Problem — Diagnosis & Repair in KL & Selangor", description: "A failing compressor causes the aircond to run without cooling. KL Renovator performs a full diagnosis to confirm if the compressor needs repair or replacement, with a transparent quote before work begins.", relatedService: "repair" },
    { slug: "aircond-pcb-problem", name: "Aircond PCB Problem", metaTitle: "Aircond PCB Board Problem & Repair KL & Selangor | KL Renovator", metaDesc: "Aircond PCB board error in KL or Selangor? KL Renovator diagnoses and replaces faulty PCB boards for all brands. Call +60182983573.", h1: "Aircond PCB Board Problem — Diagnosis & Repair in KL & Selangor", description: "A faulty PCB (printed circuit board) causes blinking error lights, erratic operation or complete shutdown. KL Renovator diagnoses PCB faults and replaces boards for all major brands.", relatedService: "repair" },
    { slug: "aircond-fan-not-working", name: "Aircond Fan Not Working", metaTitle: "Aircond Fan Not Working? Fix in KL & Selangor | KL Renovator", metaDesc: "Aircond indoor or outdoor fan not working in KL or Selangor? Fan motor replaced same-day. All brands. Call +60182983573.", h1: "Aircond Fan Not Working — Repair in KL & Selangor", description: "If your aircond indoor or outdoor fan has stopped working, the cause is usually a burnt-out fan motor or failed capacitor. KL Renovator replaces fan motors for all brands with same-day service.", relatedService: "repair" },
    { slug: "aircond-tripping-power", name: "Aircond Tripping Power", metaTitle: "Aircond Tripping MCB / Power? Fix in KL & Selangor | KL Renovator", metaDesc: "Aircond tripping your MCB or power in KL or Selangor? Electrical fault diagnosed and fixed safely. Call +60182983573.", h1: "Aircond Tripping Power — Electrical Fault Repair in KL & Selangor", description: "An aircond that repeatedly trips the MCB or power supply has an electrical fault — usually a shorted compressor, faulty capacitor or wiring issue. KL Renovator diagnoses and repairs all electrical aircond faults.", relatedService: "repair" },
    { slug: "aircond-remote-not-working", name: "Aircond Remote Not Working", metaTitle: "Aircond Remote Not Working? Fix in KL & Selangor | KL Renovator", metaDesc: "Aircond remote control not working in KL or Selangor? Remote replaced or unit receiver fixed. All brands. Call +60182983573.", h1: "Aircond Remote Control Not Working — Fix in KL & Selangor", description: "If your aircond remote is not responding, the issue could be a dead battery, faulty remote, or a damaged IR receiver on the indoor unit. KL Renovator replaces remotes and repairs IR receivers for all brands.", relatedService: "repair" },
    { slug: "aircond-indoor-unit-leaking", name: "Aircond Indoor Unit Leaking", metaTitle: "Aircond Indoor Unit Leaking Water KL & Selangor | KL Renovator", metaDesc: "Aircond indoor unit dripping or leaking water in KL or Selangor? Fixed same-day. Chemical overhaul, drain clearing. Call +60182983573.", h1: "Aircond Indoor Unit Leaking Water — Fix in KL & Selangor", description: "Water dripping from the indoor unit is the most common aircond complaint in Malaysia. Caused by blocked drain pipes or dirty drain pan. KL Renovator clears blockages and performs overhaul to permanently fix indoor unit leaks.", relatedService: "chemical-overhaul" },
    { slug: "aircond-outdoor-unit-not-running", name: "Aircond Outdoor Unit Not Running", metaTitle: "Aircond Outdoor Unit Not Running KL & Selangor | KL Renovator", metaDesc: "Aircond outdoor unit not working in KL or Selangor? Compressor or fan motor issue diagnosed and fixed. Call +60182983573.", h1: "Aircond Outdoor Unit Not Running — Diagnosis & Repair in KL & Selangor", description: "An outdoor unit that does not start or run usually indicates a compressor, fan motor or capacitor failure. KL Renovator diagnoses and repairs outdoor unit problems for all brands across KL and Selangor.", relatedService: "repair" },
    { slug: "aircond-high-electricity-bill", name: "Aircond High Electricity Bill", metaTitle: "Aircond Causing High Electricity Bill? Fix in KL & Selangor | KL Renovator", metaDesc: "Aircond causing high electricity bill in KL or Selangor? Dirty coils and low gas waste energy. Chemical wash from RM 120. Call +60182983573.", h1: "Aircond High Electricity Bill — Causes & Fix in KL & Selangor", description: "A dirty aircond coil or low refrigerant gas forces the compressor to work harder, dramatically increasing electricity consumption. A chemical wash or gas top-up by KL Renovator can reduce your bill significantly.", relatedService: "chemical-wash" },
    { slug: "aircond-weak-airflow", name: "Aircond Weak Airflow", metaTitle: "Aircond Weak Airflow? Fix in KL & Selangor | KL Renovator", metaDesc: "Aircond blowing weak air in KL or Selangor? Blocked coil or fan problem. Chemical wash from RM 120 restores airflow. Call +60182983573.", h1: "Aircond Weak Airflow — Causes & Fix in KL & Selangor", description: "Weak or reduced airflow from your aircond is caused by a blocked evaporator coil or blower wheel. A chemical wash by KL Renovator removes the blockage and fully restores airflow.", relatedService: "chemical-wash" },
    { slug: "aircond-not-turning-on", name: "Aircond Not Turning On", metaTitle: "Aircond Not Turning On? Fix in KL & Selangor | KL Renovator", metaDesc: "Aircond not turning on in KL or Selangor? Power issue, PCB fault or compressor problem diagnosed fast. Call +60182983573.", h1: "Aircond Not Turning On — Diagnosis & Repair in KL & Selangor", description: "If your aircond does not respond to the remote or power button, the cause could be a tripped MCB, faulty PCB, failed capacitor or wiring issue. KL Renovator performs a full diagnosis and fixes the problem.", relatedService: "repair" },
    { slug: "aircond-blinking-light", name: "Aircond Blinking Light Error", metaTitle: "Aircond Blinking Light Error Code KL & Selangor | KL Renovator", metaDesc: "Aircond blinking light error in KL or Selangor? Error codes diagnosed and resolved for Daikin, Panasonic, Mitsubishi & more. Call +60182983573.", h1: "Aircond Blinking Light Error — Diagnosis in KL & Selangor", description: "Blinking lights on your aircond indicate an error code. Common causes include dirty sensors, low gas, PCB faults or communication errors. KL Renovator reads error codes for all brands and resolves the root cause.", relatedService: "repair" },
    { slug: "aircond-water-dripping", name: "Aircond Water Dripping", metaTitle: "Aircond Water Dripping Fix KL & Selangor | KL Renovator", metaDesc: "Aircond dripping water in KL or Selangor? Drain pipe blockage or frozen coil. Fixed same-day. Chemical wash from RM 120. Call +60182983573.", h1: "Aircond Water Dripping — Causes & Fix in KL & Selangor", description: "Water dripping from the indoor unit is caused by a blocked drain pipe, dirty drain pan, or frozen evaporator coil. KL Renovator clears blockages and performs chemical wash or overhaul to stop the dripping.", relatedService: "chemical-wash" },
    { slug: "aircond-thermostat-problems", name: "Aircond Thermostat Problems", metaTitle: "Aircond Thermostat Problem & Fix KL & Selangor | KL Renovator", metaDesc: "Aircond thermostat not working in KL or Selangor? Temperature sensor or PCB fault diagnosed and fixed. All brands. Call +60182983573.", h1: "Aircond Thermostat Problems — Diagnosis & Fix in KL & Selangor", description: "Thermostat problems cause the aircond to run non-stop, not reach the set temperature, or shut off too early. KL Renovator diagnoses temperature sensor and thermostat faults for all brands across KL and Selangor.", relatedService: "repair" },
  ],

  brandsSupported: [
    "Daikin", "Panasonic", "Mitsubishi Electric", "York", "Acson",
    "Carrier", "Midea", "Haier", "Toshiba", "Hitachi",
    "Samsung", "LG", "Sharp", "Fujitsu", "Gree",
  ],

  services: [
    { slug: "installation", title: "New Unit Installation", short: "Professional residential and commercial AC setup with clean cable routing. Same-day installation available for all brands and HP sizes.", startPrice: 199, icon: "plug", targetProblem: "Upgrading old non-inverter systems, moving into a new office or home.", category: "both" as const },
    { slug: "basic-servicing", title: "Basic Servicing / Routine Maintenance", short: "Regular standard aircond filter cleaning and multi-point diagnostic check to maintain peak energy efficiency and extend unit lifespan.", startPrice: 99, icon: "wrench", targetProblem: "Routine 3–6 month checkup, energy efficiency optimization, preventive care.", category: "residential" as const },
    { slug: "chemical-wash", title: "Pressure Chemical Wash", short: "Deep high-pressure chemical cleaning to remove stubborn mould, dust, bacteria and dramatically improve cooling airflow and air quality.", startPrice: 120, icon: "flask-conical", targetProblem: "Slow cooling, foul smell, low airflow, dusty air extraction.", category: "both" as const },
    { slug: "chemical-overhaul", title: "Chemical Overhaul", short: "Complete dismantling of the indoor unit for the ultimate deep-clean. Permanently resolves severe water leaking, ice formation, and extreme blockage.", startPrice: 220, icon: "sparkles", targetProblem: "Water leaking, ice formation, complete blockage, system choking.", category: "both" as const },
    { slug: "gas-topup", title: "Gas Top-Up / Precision Balancing", short: "Precision refrigerant balancing and pressure level top-up for eco-friendly R32, R410A, and traditional R22 systems. Leak check included.", startPrice: 120, icon: "gauge", targetProblem: "Aircond running but blowing warm air, low gas pressure.", category: "both" as const },
    { slug: "repair", title: "Troubleshooting & Repairs", short: "Expert diagnosis and replacement of faulty aircond parts — capacitors, fan motors, sensor coils, PCB boards, or copper wiring. Quote before work.", startPrice: 88, icon: "settings", targetProblem: "Noisy outdoor unit, sudden auto shut-off, blinking timer light, wiring sparks.", category: "both" as const },
    { slug: "dismantling-relocation", title: "Dismantle & Relocation", short: "Safe and risk-free extraction of existing indoor/outdoor units with proper refrigerant pump-down and sealing. Full reinstall at new location.", startPrice: 90, icon: "move", targetProblem: "House moving, shop shifting, office renovation and AC relocation.", category: "both" as const },
    { slug: "ceiling-cassette", title: "Ceiling Cassette Solutions", short: "Heavy-duty commercial ceiling cassette servicing, chemical wash, VRF/VRV installation and scheduled maintenance for corporate and retail layouts.", startPrice: 150, icon: "layout-grid", targetProblem: "Commercial office hot spots, VRF/VRV systems, corporate annual maintenance needs.", category: "commercial" as const },
  ],

  pricing: {
    installation: {
      title: "New Unit Installation",
      rows: [
        { label: "Wall-Mounted · 1.0 HP", price: "RM 199" },
        { label: "Wall-Mounted · 1.5 HP", price: "RM 199" },
        { label: "Wall-Mounted · 2.0 HP", price: "RM 249" },
        { label: "Wall-Mounted · 2.5 HP", price: "RM 279" },
        { label: "Wall-Mounted · 3.0 HP", price: "RM 329" },
        { label: "Wall-Mounted · 4.0 HP", price: "RM 399" },
        { label: "Wall-Mounted · 5.0 HP", price: "RM 449" },
        { label: "Ceiling Cassette · 1.0 – 1.5 HP", price: "RM 290" },
        { label: "Ceiling Cassette · 2.0 – 3.0 HP", price: "RM 350" },
        { label: "Ceiling Cassette · 3.5 – 6.0 HP", price: "RM 400" },
        { label: "Additional copper pipe 1.0–1.5 HP", price: "RM 17/ft" },
        { label: "Additional copper pipe 2.0–2.5 HP", price: "RM 23/ft" },
        { label: "Additional copper pipe 3.0–3.5 HP", price: "RM 27/ft" },
        { label: "Additional wire", price: "RM 9/ft" },
        { label: "Dismantling old unit", price: "From RM 90" },
      ],
      note: "Standard professional installation includes free 7 ft copper pipe, heavy duty wiring, and system drainage layout.",
    },
    basicServicing: {
      title: "Basic Servicing / Cleaning",
      rows: [
        { label: "Wall-Mounted · 1.0 – 1.5 HP", price: "RM 99" },
        { label: "Wall-Mounted · 2.0 – 2.5 HP", price: "RM 120" },
        { label: "Wall-Mounted · 3.0 – 3.5 HP", price: "RM 150" },
        { label: "Ceiling Cassette · 1.0 – 1.5 HP", price: "RM 150" },
        { label: "Ceiling Cassette · 2.0 – 3.0 HP", price: "RM 200" },
        { label: "Ceiling Cassette · 3.5 – 5.0 HP", price: "RM 250" },
      ],
    },
    chemicalWash: {
      title: "Pressure Chemical Wash",
      rows: [
        { label: "Wall-Mounted · 1.0 – 1.5 HP", price: "RM 120" },
        { label: "Wall-Mounted · 2.0 – 2.5 HP", price: "RM 150" },
        { label: "Wall-Mounted · 3.0 HP", price: "RM 180" },
        { label: "Wall-Mounted · 4.0 – 5.0 HP", price: "RM 200" },
        { label: "Ceiling Cassette · 1.0 – 1.5 HP", price: "RM 220" },
        { label: "Ceiling Cassette · 2.0 – 3.0 HP", price: "RM 280" },
        { label: "Ceiling Cassette · 4.0 – 5.0 HP", price: "RM 350" },
        { label: "Window Unit · 1.0 – 2.0 HP", price: "RM 130" },
        { label: "Window Unit · 2.5 – 3.0 HP", price: "RM 160" },
      ],
    },
    chemicalOverhaul: {
      title: "Chemical Overhaul",
      rows: [
        { label: "Wall-Mounted · 1.0 – 1.5 HP", price: "RM 220" },
        { label: "Wall-Mounted · 2.0 – 2.5 HP", price: "RM 280" },
        { label: "Wall-Mounted · 3.0 – 3.5 HP", price: "RM 350" },
        { label: "Ceiling Cassette · 1.0 – 3.0 HP", price: "RM 380 – 480" },
      ],
    },
    gasTopup: {
      title: "Gas Top-Up / Precision Balancing",
      rows: [
        { label: "R22 · 1.0 HP", price: "RM 120" },
        { label: "R22 · 1.5 – 2.0 HP", price: "RM 150" },
        { label: "R22 · 2.5 – 3.0 HP", price: "RM 180" },
        { label: "R410A · 1.0 HP", price: "RM 150" },
        { label: "R410A · 1.5 – 2.0 HP", price: "RM 180" },
        { label: "R410A · 2.5 – 3.0 HP", price: "RM 200" },
        { label: "R32 · 1.0 HP", price: "RM 180" },
        { label: "R32 · 1.5 – 2.0 HP", price: "RM 200" },
        { label: "R32 · 2.5 – 3.0 HP", price: "RM 220" },
      ],
    },
    repair: {
      title: "Troubleshooting & Component Repair",
      rows: [
        { label: "Diagnostic Fee (waived with repair)", price: "RM 88" },
        { label: "Capacitor Replacement", price: "RM 180" },
        { label: "Copper Sensor / Thermistor", price: "RM 150" },
        { label: "Fan Motor", price: "RM 250 – 450" },
        { label: "PCB / Main Board", price: "RM 300 – 600" },
        { label: "Drain Pipe Clearing", price: "RM 120" },
        { label: "Drain Pump Installation", price: "RM 300 – 400" },
        { label: "Compressor Replacement", price: "RM 600 – 2,000" },
        { label: "Remote Control Replacement", price: "RM 80 – 130" },
      ],
    },
    dismantling: {
      title: "Dismantling & Relocation",
      rows: [
        { label: "Dismantle Only", price: "RM 90" },
        { label: "Dismantle + Reinstall", price: "RM 290" },
        { label: "Dismantle + Relocate", price: "RM 350" },
      ],
    },
    materials: {
      title: "Additional Materials Pricing",
      rows: [
        { label: "Copper Pipe 1.0 – 1.5 HP", price: "RM 17/ft" },
        { label: "Copper Pipe 2.0 – 2.5 HP", price: "RM 23/ft" },
        { label: "Copper Pipe 3.0 – 3.5 HP", price: "RM 27/ft" },
        { label: "Wire", price: "RM 9/ft" },
        { label: "Standard Outdoor Bracket", price: "RM 45" },
        { label: "Indoor Universal Bracket", price: "RM 30" },
        { label: "PVC Casing Wire/Copper Pipe", price: "RM 6 – 12/ft" },
        { label: "Electrical Plug Point Installation", price: "RM 100" },
        { label: "Wall Hacking & Concealment Work", price: "RM 6/ft" },
        { label: "High-Rise / Difficult Access Charge", price: "RM 50 – 150" },
        { label: "Standard Metal Cable Tray", price: "RM 15/ft" },
      ],
    },
    contracts: {
      title: "Annual Corporate & Residential Maintenance Contracts",
      rows: [
        { label: "Residential Package · 2 – 4 units / year contract", price: "RM 499" },
        { label: "Residential Package · 5+ units / year contract", price: "RM 999" },
        { label: "Commercial Package · 5 – 10 units / year contract", price: "RM 1,999" },
        { label: "Commercial Package · 10+ units / year contract", price: "RM 3,499" },
      ],
    },
  },

  volumeDiscounts: [
    { units: "2 – 3 units", off: "5% off instant booking discount" },
    { units: "4 – 8 units", off: "10% off instant booking discount" },
    { units: "8+ units", off: "15% off instant booking discount" },
  ],

  stats: [
    { label: "Happy Klang Valley Customers", value: "5,000+" },
    { label: "Years HVAC Experience", value: "10+" },
    { label: "5-Star Verified Reviews", value: "500+" },
    { label: "Emergency Response Time", value: "< 30 min" },
  ],

  links: {
    whatsapp: "https://wa.me/60182983573",
    facebook: "https://www.facebook.com/share/1HV3kAqC6V/",
    instagram: "https://www.instagram.com/klrenovator?igsh=MTNqb3p1NDExZ3Boeg==",
    tiktok: "https://www.tiktok.com/@klrenovator?_r=1&_t=ZS-96tR1k7aVU5",
    youtube: "https://www.youtube.com/@klrenovator",
    googleMaps: "https://maps.app.goo.gl/dG5WWYBCotRQzvRJA",
    googleBusiness: "https://share.google/HhXvqWDkefZ5bzNdL",
  },
};
