export const pricing = {
    installation: {
      title: "New Unit Installation",
      rows: [
        { label: "Wall-Mounted · 1.0 HP", price: "RM 199" },
        { label: "Wall-Mounted · 1.5 HP", price: "RM 199" },
        { label: "Wall-Mounted · 2.0 HP", price: "RM 249" },
        { label: "Wall-Mounted · 2.5 HP", price: "RM 279" },
        { label: "Wall-Mounted · 3.0 HP", price: "RM 329" },
        { label: "Wall-Mounted · 4.0 HP", price: "RM 399" },
        { label: "Wall-Mounted · 5.0 HP", price: "RM 449" },
        { label: "Ceiling Cassette · 1.0 – 1.5 HP", price: "RM 290" },
        { label: "Ceiling Cassette · 2.0 – 3.0 HP", price: "RM 350" },
        { label: "Ceiling Cassette · 3.5 – 6.0 HP", price: "RM 400" },
        { label: "Window Unit · 1.0 – 1.5 HP", price: "RM 199" },
        { label: "Window Unit · 2.0 – 2.5 HP", price: "RM 249" },
      ],
      note: "Standard installation includes 7ft copper pipe, insulation, electrical wire, and drain pipe free. Anything beyond 7ft, or any bracket / casing / electrical / access work, is charged per the Additional Materials & Special Charges rates below.",
    },
    basicServicing: {
      title: "Basic Servicing / Cleaning",
      rows: [
        { label: "Wall-Mounted · 1.0 – 1.5 HP", price: "RM 99" },
        { label: "Wall-Mounted · 2.0 – 2.5 HP", price: "RM 120" },
        { label: "Wall-Mounted · 3.0 – 3.5 HP", price: "RM 150" },
        { label: "Ceiling Cassette · 1.0 – 1.5 HP", price: "RM 150" },
        { label: "Ceiling Cassette · 2.0 – 3.0 HP", price: "RM 200" },
        { label: "Ceiling Cassette · 3.5 – 5.0 HP", price: "RM 250" },
      ],
    },
    chemicalWash: {
      title: "Pressure Chemical Wash",
      rows: [
        { label: "Wall-Mounted · 1.0 – 1.5 HP", price: "RM 120" },
        { label: "Wall-Mounted · 2.0 – 2.5 HP", price: "RM 150" },
        { label: "Wall-Mounted · 3.0 HP", price: "RM 180" },
        { label: "Wall-Mounted · 4.0 – 5.0 HP", price: "RM 200" },
        { label: "Ceiling Cassette · 1.0 – 1.5 HP", price: "RM 220" },
        { label: "Ceiling Cassette · 2.0 – 3.0 HP", price: "RM 280" },
        { label: "Ceiling Cassette · 4.0 – 5.0 HP", price: "RM 350" },
        { label: "Window Unit · 1.0 – 2.0 HP", price: "RM 130" },
        { label: "Window Unit · 2.5 – 3.0 HP", price: "RM 160" },
      ],
    },
    chemicalOverhaul: {
      title: "Chemical Overhaul",
      rows: [
        { label: "Wall-Mounted · 1.0 – 1.5 HP", price: "RM 220" },
        { label: "Wall-Mounted · 2.0 – 2.5 HP", price: "RM 280" },
        { label: "Wall-Mounted · 3.0 – 3.5 HP", price: "RM 350" },
      ],
    },
    gasTopup: {
      title: "Gas Top-Up & Refill (Per PSI)",
      rows: [
        { label: "R22 Gas Refill", price: "RM 2.50 / PSI" },
        { label: "R410A Gas Refill", price: "RM 3.00 / PSI" },
        { label: "R32 Gas Refill", price: "RM 3.00 / PSI" },
        { label: "Gas Leak Repair", price: "RM 120 / leak" },
      ],
      note: "Gas top-up is charged based on the actual PSI required after inspection by our technician. We only refill the amount needed and provide transparent pricing with no hidden charges.",
    },
    repair: {
      title: "Troubleshooting & Component Repair",
      rows: [
        { label: "Diagnostic Fee (waived with repair)", price: "RM 88" },
        { label: "Capacitor Replacement", price: "RM 150 – 250" },
        { label: "Fan Motor Replacement", price: "RM 350 – 480" },
        { label: "PCB Board Replacement", price: "RM 350 – 600" },
        { label: "Gas Leak Repair", price: "RM 120 / leak" },
        { label: "Temperature Sensor Replacement", price: "RM 150 – 250" },
        { label: "Contactor Replacement", price: "RM 150 – 200" },
        { label: "Drain Pump Replacement", price: "RM 350 – 550" },
        { label: "Compressor Replacement", price: "RM 800 – 2,000" },
      ],
    },
    dismantling: {
      title: "Dismantling & Relocation",
      rows: [
        { label: "Dismantle Only (indoor + outdoor)", price: "RM 90" },
        { label: "Dismantle + Reinstall Same Place (standard)", price: "RM 250" },
        { label: "Dismantle + Reinstall Same Place (2.0–2.5 HP)", price: "RM 290" },
        { label: "Dismantle + Reinstall Other Place", price: "RM 350" },
      ],
      note: "7ft copper pipe, insulation, electrical wire, and drain pipe are free with reinstallation. Beyond 7ft, or any bracket/casing/electrical/access work, is charged per the Additional Materials & Special Charges rates.",
    },
    materials: {
      title: "Additional Materials Pricing",
      rows: [
        { label: "Copper Pipe 1.0 – 1.5 HP", price: "RM 17/ft" },
        { label: "Copper Pipe 2.0 – 2.5 HP", price: "RM 23/ft" },
        { label: "Copper Pipe 3.0 – 3.5 HP", price: "RM 27/ft" },
        { label: "Electrical Wire", price: "RM 9/ft" },
        { label: "Insulation", price: "RM 7/ft" },
        { label: "Drain Pipe beyond 7 ft", price: "RM 5/ft" },
        { label: "Standard Compressor / Outdoor Bracket", price: "RM 45" },
        { label: "Heavy Duty Compressor / Outdoor Bracket", price: "RM 70" },
        { label: "Indoor Universal Bracket", price: "RM 35" },
        { label: "Small PVC Casing (Electrical Wire)", price: "RM 6/ft" },
        { label: "Large PVC Casing (Copper Pipe + Wire + Insulation)", price: "RM 12/ft" },
        { label: "Electrical Plug Point Installation", price: "RM 100" },
        { label: "Wall Hacking & Concealment Work", price: "RM 6/ft" },
        { label: "High-Rise / Difficult Access Charge", price: "RM 50 – 150" },
        { label: "Standard Metal Cable Tray", price: "RM 15/ft" },
      ],
    },
    contracts: {
      title: "Annual Maintenance Contract (AMC) Plans",
      rows: [
        { label: "AMC Basic · per unit / year (2 basic services + 1 chemical wash)", price: "RM 299" },
        { label: "AMC Standard · per unit / year (2 basic services + 2 chemical washes + free emergency check)", price: "RM 499" },
        { label: "AMC Premium · per unit / year (4 services + 2 chemical washes + 1 overhaul + 15% repair discount)", price: "RM 899" },
      ],
      note: "Prices per wall-mounted 1.0–1.5 HP unit. Multi-unit and commercial discounts quoted on enquiry — WhatsApp +60182983573.",
    },
  };
