export const services = [
    { slug: "installation", title: "New Unit Installation", short: "Professional aircond installation from RM199 — wall-mounted, ceiling cassette & window units for all 20 brands. Same-day available, 1-month workmanship warranty, vacuum pump commissioning.", startPrice: 199, icon: "plug", targetProblem: "New home setup, upgrading old systems, moving into new office or condo.", category: "both" as const },
    { slug: "emergency", title: "Emergency Aircond Repair", short: "Same-day rapid emergency response for complete aircond breakdowns, heavy water leaks, outdoor unit failures, and urgent repairs across KL & Selangor.", startPrice: 88, icon: "alert-triangle", targetProblem: "Sudden complete breakdown, heavy water leak, MCB tripping, burning smell.", category: "both" as const },
    { slug: "basic-servicing", title: "Basic Servicing / Routine Maintenance", short: "Regular standard aircond filter cleaning and multi-point diagnostic check to maintain peak energy efficiency and extend unit lifespan.", startPrice: 99, icon: "wrench", targetProblem: "Routine 3–6 month checkup, energy efficiency checks, preventive care.", category: "residential" as const },
    { slug: "chemical-wash", title: "Pressure Chemical Wash", short: "Deep high-pressure chemical cleaning to remove stubborn mould, dust, bacteria and dramatically improve cooling airflow and air quality.", startPrice: 120, icon: "flask-conical", targetProblem: "Slow cooling, foul smell, low airflow, dusty air extraction.", category: "both" as const },
    { slug: "chemical-overhaul", title: "Chemical Overhaul (Wall-Mounted Aircon only)", short: "Wall-Mounted Aircon only — complete dismantling of the indoor unit for the ultimate deep-clean. Permanently resolves severe water leaking, ice formation, and extreme blockage. Other aircon types require a separate on-site quote.", startPrice: 420, icon: "sparkles", targetProblem: "Water leaking, ice formation, complete blockage, system choking — wall-mounted units.", category: "both" as const },
    { slug: "gas-topup", title: "Gas Top-Up / Precision Balancing", short: "Precision refrigerant balancing and pressure level top-up. Charged per PSI: R32 (RM3), R410A (RM3), R22 (RM2.50). Leak check included.", startPrice: 2.5, icon: "gauge", targetProblem: "Aircond running but blowing warm air, low gas pressure.", category: "both" as const },
    { slug: "repair", title: "Troubleshooting & Repairs", short: "Expert diagnosis and replacement of faulty aircond parts — capacitors, fan motors, sensor coils, PCB boards, or copper wiring. Quote before work.", startPrice: 88, icon: "settings", targetProblem: "Noisy outdoor unit, sudden auto shut-off, blinking timer light, wiring sparks.", category: "both" as const },
    { slug: "dismantling-relocation", title: "Dismantle & Relocation", short: "Safe and risk-free extraction of existing indoor/outdoor units with proper refrigerant pump-down and sealing. Full reinstall at new location.", startPrice: 90, icon: "move", targetProblem: "House moving, shop shifting, office relocation/shifting.", category: "both" as const },
    { slug: "ceiling-cassette", title: "Ceiling Cassette Solutions", short: "Heavy-duty commercial ceiling cassette servicing, chemical wash, installation and scheduled maintenance for corporate and retail layouts.", startPrice: 150, icon: "layout-grid", targetProblem: "Commercial office hot spots, multi-unit ceiling cassette systems, corporate annual maintenance needs.", category: "commercial" as const },
    { slug: "maintenance-contract", title: "Maintenance Contract (AMC)", short: "Annual aircond maintenance plans with quarterly servicing, priority scheduling, and free emergency checks. Save up to 30% vs one-off bookings. From RM 299/year.", startPrice: 299, icon: "shield-check", targetProblem: "Regular maintenance scheduling, long-term cost savings, priority emergency response, commercial multi-unit plans.", category: "both" as const },
  ];
